onaio/onadata

README.rst

Correct link to installation instructions

---

docs/profiles.rst

missing password and last_name

specify complete set of required fields

---

onadata/apps/api/tests/viewsets/test_abstract_viewset.py
onadata/apps/api/tests/viewsets/test_connect_viewset.py
onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
onadata/libs/serializers/user_profile_serializer.py

validate password during email update

---

onadata/apps/restservice/tests/viewsets/test_restservicesviewset.py
onadata/libs/serializers/fields/xform_field.py

form id validation

---

onadata/apps/api/tests/fixtures/tutorial/instances/tutorial_2012-06-27_11-27-53_w_uuid_edited_blank.xml
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/logger/models/instance.py

update full json dict on submission edit

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/libs/serializers/project_serializer.py

Add `id_string` to the form info returned by the projects endpoint.

---

onadata/apps/api/management/commands/fix_readonly_role_perms.py
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/libs/permissions.py

added can view xform all perm to readonly

---

onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/api/viewsets/dataview_viewset.py
onadata/apps/logger/models/data_view.py
onadata/apps/viewer/models/parsed_instance.py
onadata/apps/viewer/parsed_instance_tools.py

Enables search on a filtered dataset.

filter dataset search

---

onadata/apps/api/permissions.py
onadata/apps/api/tests/viewsets/test_widget_viewset.py
onadata/libs/permissions.py

closes #831 
closes https://github.com/onaio/zebra/issues/4685

Allow "readonly" and "readonly no download" to edit widgets

---

onadata/libs/tests/utils/test_chart_tools.py
onadata/libs/utils/chart_tools.py

Support submitted by charts

---

onadata/libs/tests/utils/test_chart_tools.py
onadata/libs/utils/chart_tools.py

include submitted by in the allowed group by fields

---

onadata/apps/api/tests/viewsets/test_abstract_viewset.py
onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/tools.py
onadata/apps/api/viewsets/organization_profile_viewset.py
onadata/libs/serializers/fields/organization_field.py
onadata/libs/serializers/organization_member_serializer.py

closes #843 
closes https://github.com/onaio/zebra/issues/4672

validate org account when adding org members

---

docs/profiles.rst
onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
onadata/libs/filters.py

Return user profiles if a list of usernames has been provided or a user is authenticated

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/viewsets/project_viewset.py
onadata/apps/main/management/commands/create_metadata_for_kpi_deployed_forms.py
onadata/apps/main/models/meta_data.py
onadata/libs/serializers/project_serializer.py

Add xform metadata for forms published by kpi

---

onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/api/viewsets/dataview_viewset.py

add submitted and duration field in dataview charts

---

onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/api/viewsets/xform_viewset.py
onadata/libs/mixins/cache_control_mixin.py

Uses django utility function to modify cache control and disables cache in form definition endpoint.

Form xml cache fix

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py

Closes https://github.com/onaio/core/issues/1339

Force authentication for linked dataset media attachment

---

onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/main/forms.py

xml form upload

---

onadata/libs/tests/utils/test_chart_tools.py
onadata/libs/utils/chart_tools.py

Handle charts attribute error

---

onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/api_export_tools.py
onadata/libs/utils/export_tools.py

Checks and retreives the last pending export within 5 min

---

onadata/libs/tests/utils/test_api_export_tools.py
onadata/libs/tests/utils/test_csv_import.py
onadata/libs/utils/api_export_tools.py
onadata/libs/utils/csv_import.py

BacklogLimitExceeded exception eventually stops, hence returning a `PENDING` status allows continued checking since the export/import is usually still in progress, the task is not cancelled.
Fixes #914

handle BacklogLimitExceeded exception

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/libs/filters.py

Allows preview of form without allowing submissions for those who require authentication.

drop check of submit permission from form list or xform download

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/libs/filters.py

Revert "drop check of submit permission from form list or xform download"

---

onadata/libs/utils/backup_tools.py
onadata/libs/utils/export_builder.py

set ZIP_DEFLATED and allowZip64=True in creating zip files

---

onadata/apps/api/viewsets/xform_viewset.py
onadata/libs/utils/csv_import.py

switch to using django storage for csv import processing

---

onadata/apps/logger/models/xform.py
onadata/apps/logger/tests/models/test_xform.py
onadata/libs/utils/logger_tools.py

soft deleted xforms should not be downloadable

---

docs/install.rst

Make the Postgres setup simpler and easy to follow.
Depends https://github.com/onaio/docker-builds/pull/14

Update Postgres install docs to use docker-compose.

---

onadata/apps/viewer/tests/test_export_builder.py
onadata/libs/utils/export_builder.py

Check correct SPSS variable for select one fields

---

onadata/libs/serializers/export_serializer.py
onadata/libs/tests/serializers/test_export_serializer.py

1058 add export url to exports endpoint

---

onadata/apps/logger/models/data_view.py
onadata/apps/logger/tests/models/test_data_view.py

addresses #1066 by avoiding including columns in the sql query
closes #1066

set fields programmatically for filtered datsets

---

onadata/apps/main/urls.py
onadata/apps/main/views.py
onadata/libs/templates/oauth2_provider/authorize.html

A fix to issue #1062 which adds the ability for a user to log in as another user
when authenticating via OAuth.

KEJ: ADD ABILITY TO LOG IN AS A DIFFERENT USER

---

onadata/apps/api/permissions.py
onadata/apps/api/tests/viewsets/test_export_viewset.py
onadata/apps/api/viewsets/export_viewset.py
onadata/libs/filters.py

Fixes: #1077
Ensure that exports of public projects are allowed for all users whether
they are authenticated or not.

Allow unrestricted exports on public project

---

docs/data.rst

Discovered inconsistency while querying the API with curl, the changed version is the actual format a single record is returned in, as it should be

correct data single record return example

---

onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/main/urls.py

Ensure Accessing Dataviews With Invalid URLs Results In A 404

---

onadata/libs/tests/utils/test_chart_tools.py

Test get_choice_label to ensure it does not fail for non-string values

---

.pylintrc
onadata/apps/logger/models/xform.py
onadata/apps/logger/views.py
onadata/apps/main/views.py
onadata/apps/viewer/views.py
onadata/libs/tests/utils/test_viewer_tools.py
onadata/libs/utils/common_tags.py
onadata/libs/utils/viewer_tools.py

- Filter deleted forms in classic web views
- code cleanup and documentation

Filter deleted forms in classic web views

---

docs/data.rst
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/libs/filters.py

Add media_all_received as a data filter parameter

---

onadata/libs/permissions.py

Hopefully faster, the joins can be quite taxing in high traffic with a large dataset.

Re-implement users with object permissions

---

onadata/apps/viewer/models/data_dictionary.py
onadata/libs/utils/logger_tools.py

Propagate exceptions when handling external choices.

---

onadata/apps/api/permissions.py
onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
onadata/apps/api/viewsets/briefcase_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/apps/api/viewsets/xform_submission_viewset.py
onadata/libs/mixins/openrosa_headers_mixin.py
onadata/libs/serializers/data_serializer.py
onadata/libs/utils/dict_tools.py
onadata/libs/utils/logger_tools.py

Closes https://github.com/onaio/onadata/issues/1143

Rapidpro to Ona Submissions

---

onadata/apps/logger/tests/test_form_submission.py
onadata/apps/restservice/signals.py
onadata/apps/viewer/models/parsed_instance.py
onadata/apps/viewer/signals.py
onadata/libs/utils/logger_tools.py
onadata/libs/utils/osm.py

- Use signals to call webhooks
- Resend submission t webhook when OSM data has been processed, fix #1130 
- pylint cleanup

Refactor calling webhooks to use django signals.

---

onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/libs/data/__init__.py

parse_int should return None for empty string.

---

docs/submissions.rst
onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
onadata/apps/api/viewsets/data_viewset.py
onadata/apps/api/viewsets/xform_submission_viewset.py
onadata/libs/renderers/renderers.py
onadata/libs/serializers/data_serializer.py
onadata/libs/utils/dict_tools.py

Closes https://github.com/onaio/onadata/issues/1118

Add FLOIP submission endpoint

---

onadata/libs/serializers/data_serializer.py

Closes https://github.com/onaio/onadata/issues/1167

Use a ListSerializer for FLOIP submissions

---

docs/data.rst
docs/forms.rst
docs/submissions.rst
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/libs/renderers/renderers.py
onadata/libs/serializers/data_serializer.py

Closes https://github.com/onaio/onadata/issues/1117

Convert JSON dict to FLOIP list

---

docs/data.rst
docs/forms.rst
docs/submissions.rst

Fixes a few issues on FLOIP docs.

Edit FLOIP docs

---

onadata/apps/api/tests/fixtures/flow-results-example-1.json
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/urls.py
onadata/apps/api/viewsets/data_viewset.py
requirements/base.in
requirements/base.pip
requirements/dev.pip

1173 add bulk delete functionality

---

onadata/apps/api/tests/mocked_data.py
onadata/apps/api/tests/viewsets/test_export_viewset.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/api/viewsets/dataview_viewset.py
onadata/apps/viewer/models/parsed_instance.py
onadata/apps/viewer/parsed_instance_tools.py
onadata/apps/viewer/tasks.py
onadata/libs/filters.py
onadata/libs/permissions.py
onadata/libs/tests/test_permissions.py
onadata/libs/utils/api_export_tools.py

Meta permissions should apply to exports list

---

onadata/libs/tests/utils/test_csv_builder.py
onadata/libs/utils/csv_builder.py
onadata/libs/utils/export_builder.py
onadata/settings/docker.py

Prevent duplacate extra columns

---

.travis.yml
onadata/apps/logger/migrations/0044_xform_hash_sql_update.py

XForm MD5 Hash DB Migration

---

onadata/apps/logger/management/commands/reapplyperms.py

Add management command to reapply permissions

---

onadata/apps/api/permissions.py
onadata/apps/api/tests/viewsets/test_export_viewset.py
onadata/libs/filters.py

Return exports for all public forms to authenticated users

---

onadata/apps/api/viewsets/xform_viewset.py

Use queryset_iterator in XFormViewSet streaming

---

onadata/apps/api/tools.py

UK|KJ: Set form permission to the user who uploaded a form

---

onadata/apps/api/tests/mocked_data.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/libs/utils/viewer_tools.py

Improve Enketo HTTP 502 Error Message

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/libs/filters.py

- Add formID filter class to XFormListViewSet
- Add test
Fix #1246

formID filter for formList

---

onadata/libs/serializers/xform_serializer.py

Update number of submissions count for forms in merged datasets

---

onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
onadata/apps/api/tests/viewsets/test_user_viewset.py
onadata/apps/api/viewsets/organization_profile_viewset.py
onadata/apps/api/viewsets/user_profile_viewset.py
onadata/apps/api/viewsets/user_viewset.py
onadata/libs/filters.py

Applies to /orgs /users /profiles endpoints.

Only return users who are still active.

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/libs/serializers/xform_serializer.py

Include csv query_params for linked datasets in media link.

---

onadata/apps/messaging/README.md
onadata/libs/utils/model_tools.py

Add documentation for MQTT settings and topics.

Add MQTT documentation

---

onadata/apps/messaging/README.md
onadata/apps/messaging/backends/mqtt.py
onadata/apps/messaging/constants.py
onadata/apps/messaging/serializers.py
onadata/apps/messaging/tests/test_backends_mqtt.py
onadata/apps/messaging/tests/test_messaging_viewset.py

- Enrich MQTT payload for the different target object types
- Add timestamp to MessagingSerializer
Fix: #1331
Fix: #1332

Improve messaging

---

.travis.yml
onadata/apps/logger/management/commands/import_forms.py
onadata/apps/logger/models/attachment.py
onadata/apps/logger/models/merged_xform.py
onadata/apps/logger/models/note.py
onadata/apps/main/models/__init__.py
onadata/apps/sms_support/autodoc.py
onadata/apps/sms_support/providers/__init__.py
onadata/apps/sms_support/tests/test_notallowed.py
onadata/apps/sms_support/views.py
onadata/apps/viewer/management/commands/import_forms.py
onadata/libs/tests/utils/test_export_builder.py
onadata/libs/utils/export_builder.py
onadata/libs/utils/export_tools.py

Fix: #1309
Note: this is to be merged into the python-2-3 branch

Dont use relative imports

---

onadata/apps/api/management/commands/reset_rest_services.py

Fix: #1314 
Note: to be merged into python-2-3 branch

Refactor reset_rest_services.py

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/libs/serializers/project_serializer.py
onadata/libs/tests/serializers/test_project_serializer.py

Test creating project with same name

---

requirements/base.in
requirements/base.pip

Use pyxform master branch.

---

onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/libs/serializers/project_serializer.py

Filter deleted dataviews on project page and add test

---

README.rst

Acknowledge the security contribution made by Danish Tariq on 1st April 2018.

Acknowledge Danish Tariq's Security Contribution

---

CHANGES.rst
onadata/__init__.py

Change version to 1.14.0 and add changes in new version

version 1.14.0

---

onadata/apps/logger/models/xform.py
onadata/apps/logger/tests/models/test_xform.py
onadata/libs/renderers/renderers.py
onadata/libs/serializers/floip_serializer.py
onadata/libs/utils/logger_tools.py

Update check_xform_uuid() to only check for non deleted forms

---

CHANGES.rst
onadata/libs/tests/utils/test_csv_builder.py
onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/briefcase_client.py
onadata/libs/utils/csv_builder.py
onadata/libs/utils/export_builder.py
onadata/libs/utils/export_tools.py

- Add value_select_multiples to flat CSV exports
- Add binary_select_multiples as part of export params
- Download manifiest URL if it exists

Support value_select_multiples option in flat CSV

---

CHANGES.rst
onadata/apps/api/tests/viewsets/test_team_viewset.py
onadata/apps/api/viewsets/project_viewset.py
onadata/apps/api/viewsets/team_viewset.py

The boolean value for remove is in data as a string. This checks if the value is True

Check value of remove

---

CHANGES.rst
onadata/libs/tests/utils/test_export_builder.py
onadata/libs/utils/export_builder.py

Fix TypeError exception in SPSS exports with external choices

---

.gitignore
Dockerfile
docker-compose.yml
docker/docker-entrypoint.sh
docs/proposals/export-labels-for-selects.md
onadata/apps/logger/models/xform.py
onadata/apps/viewer/models/export.py
onadata/libs/tests/utils/test_csv_builder.py
onadata/libs/tests/utils/test_export_builder.py
onadata/libs/utils/csv_builder.py
onadata/libs/utils/export_builder.py
onadata/libs/utils/export_tools.py

Adds the option to export Select One and Select Multiple question
choice labels as part of the data.
Fix #1427

Support exporting labels for selects in the data

---

onadata/libs/tests/utils/test_image_tools.py
onadata/libs/utils/image_tools.py

- Open image directly instead of using StringIO
- Add test to resize image
Fix #1440 
Fix https://github.com/onaio/zebra/issues/5405

Fix Image resize

---

onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/tests/viewsets/test_metadata_viewset.py
onadata/apps/api/tests/viewsets/test_team_viewset.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/api/tools.py
onadata/libs/models/share_team_project.py
onadata/libs/permissions.py
onadata/libs/utils/common_tags.py

Update user roles according to xform meta permissions provided.
Fixes #1479

Fix failing xform meta permissions

---

docs/projects.rst

Update projects documentation

---

requirements/base.pip
requirements/dev.pip

Upgrade kombu

---

onadata/apps/api/urls.py

Provide base_name for hyperlinked user field.

---

onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/libs/serializers/dataview_serializer.py
onadata/libs/tests/serializers/test_dataview_serializer.py

Fixes https://github.com/onaio/onadata/issues/1498

Fix duplication of the same Dataview  for the same Xform

---

onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/api/viewsets/xform_viewset.py
onadata/settings/common.py

Return better error messages on invalid csv/xls imports

---

onadata/libs/tests/utils/test_api_export_tools.py
onadata/libs/utils/api_export_tools.py

Assign function call `job.result` a variable to avoid errors when the return value changes in subsequent calls.
fixes #999

Cache `job.result` function

---

onadata/apps/api/tests/viewsets/test_user_viewset.py
onadata/apps/api/viewsets/connect_viewset.py
onadata/apps/api/viewsets/organization_profile_viewset.py
onadata/apps/api/viewsets/user_profile_viewset.py
onadata/apps/api/viewsets/user_viewset.py

Fix hyperlinked relationship using email

---

onadata/apps/api/tests/viewsets/test_user_viewset.py
onadata/apps/api/viewsets/connect_viewset.py
onadata/apps/api/viewsets/organization_profile_viewset.py
onadata/apps/api/viewsets/user_profile_viewset.py
onadata/apps/api/viewsets/user_viewset.py

Revert "Fix hyperlinked relationship using email"

---

onadata/apps/api/viewsets/user_profile_viewset.py

Fix TypeError on change_password when format is supplied on the URL.

---

onadata/apps/viewer/views.py

Results in a single query rather than two queries.

Optimize attachment query by removing sort and count.

---

CHANGES.rst
onadata/__init__.py

Bump version

---

onadata/libs/tests/utils/fixtures/date.csv
onadata/libs/tests/utils/test_csv_import.py
onadata/libs/utils/common_tags.py
onadata/libs/utils/csv_import.py

Converts date from `d/m/yyyy` to `yyyy-mm-dd`
CSV date is in the format `yyyy-mm-dd`. When this file is opened by excel, the date format changes  to `d/m/yyyy`. This format is maintained after saving. 
fixes #1577

Convert excel date format to csv format

---

CHANGES.rst
onadata/__init__.py

Update changes.rst file

---

onadata/apps/main/templates/form_photos.html
onadata/apps/main/views.py

This addresses the implementation mentioned here https://github.com/onaio/onadata/issues/1560#issuecomment-469560305
fixes #1560

Only load current Image being viewed on `forms/{username}/photos`

---

onadata/apps/api/tests/viewsets/test_metadata_viewset.py
onadata/apps/main/models/meta_data.py
onadata/libs/serializers/metadata_serializer.py
onadata/libs/utils/common_tags.py

fixes #1585.
Add metadata function for submission review data_type.
Ensure only single submission-review metadata for a form.

Submission review meta

---

onadata/apps/main/forms.py
onadata/libs/utils/logger_tools.py

Encode text_xls_form string

---

CHANGES.rst
onadata/__init__.py

Upgrade to v2.0.0

---

onadata/apps/viewer/models/parsed_instance.py
onadata/libs/utils/logger_tools.py

Rename vars whose name is async

---

onadata/libs/authentication.py

When temptoken authentication is preceded by basic/digest authentication that generates the temptoken, the temptoken authentication fails.
This is because the changes in master db have not been reflected on the replica db yet.
Here we pin the the temptoken authentication to master db.
fixes #1616 

Pin temptoken authentication to master.

---

CHANGES.rst
onadata/__init__.py

Upgrade version to v2.0.3

---

onadata/libs/tests/utils/test_csv_import.py
onadata/libs/utils/csv_import.py

When job.info is any other type other than a dictionary, it causes errors.
fixes #1624

Fix TypeError on getting async csv import status

---

CHANGES.rst
onadata/__init__.py

Bump version
Updates changes file

Onadata v2.0.4

---

onadata/libs/authentication.py

I don't know why this is flagged as an import error other environments other than local. 
This is a cyclic import fix.
fixes #1632

Fix import error

---

onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/viewsets/data_viewset.py

Capture users who delete submissions

---

onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/export_builder.py

Include check for label value during sav exports

---

onadata/apps/api/tests/viewsets/test_attachment_viewset.py
onadata/apps/api/viewsets/attachment_viewset.py
onadata/libs/filters.py
onadata/libs/utils/common_tags.py

Include filter for image attachements

---

onadata/apps/logger/models/instance.py
onadata/apps/logger/tests/models/test_instance.py

return integer representation of negative values

---

onadata/libs/authentication.py
onadata/libs/tests/utils/test_cache_tools.py
onadata/libs/utils/cache_tools.py

Use a valid cache key

---

onadata/apps/api/tests/viewsets/test_connect_viewset.py
onadata/libs/tests/utils/test_cache_tools.py
onadata/libs/utils/cache_tools.py

Prevents maximum recursion depth error.
Fixes #1661

Use hashed keys for safe cache keys

---

docs/media.rst

Includes documentation about filtering the media endpoint
Builds on #1645

Attachment endpoint documentation

---

onadata/apps/messaging/backends/base.py

Use master database when calling notification backends

---

onadata/apps/api/models/odk_token.py
onadata/apps/api/storage.py
onadata/apps/logger/tests/test_digest_authentication.py

Retrieve user using the users `email` rather than their username

Fix ODKTokenAccountStorage user retrieve issue

---

onadata/libs/authentication.py
onadata/libs/tests/test_authentication.py

Fix MemcachedKeyLengthError when locking out users

---

onadata/libs/serializers/xform_serializer.py

Return XForm version even if the version is not a number

---

onadata/apps/api/tests/models/test_organization_profile.py
onadata/apps/api/tools.py

Add optional `ORG_ON_CREATE_IS_ACTIVE` setting

Add a way to deactivate organizations by default on create 

---

onadata/apps/api/viewsets/xform_list_viewset.py

Stop lower casing usernames on XFormListViewset `filter_queryset`

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.MD

Add Contribution guideline, Issue and Pull request template

---

onadata/libs/serializers/organization_serializer.py

Assign members excluded queryset for filter to take effect

---

Dockerfile

Update Dockerfile
docker-compose build
Replacing jonathonf py3.6 ppa to deadsnakes
Closes #1746

update py3.6 ppa with deadsnakes source;

---

CONTRIBUTING.MD

- Include a new requirement concerning signed commits withing the contributing guideline
- Signed commits will be a requirement for Pull requests to be merged in the repository.... 
Closes #1778

Update Contributing guideline

---

CHANGES.rst

Update change logs

---

onadata/apps/api/viewsets/xform_viewset.py
onadata/apps/main/management/commands/create_enketo_express_urls.py
onadata/apps/main/management/commands/update_enketo_urls.py
onadata/libs/serializers/xform_serializer.py
onadata/libs/tests/utils/test_viewer_tools.py
onadata/libs/utils/viewer_tools.py

- Rename variable `gen_consistent` to `consistent_urls`
CI Tests
None

Rename variable 'gen_consistent' to 'consistent_urls'

---

CHANGES.rst
onadata/__init__.py

Tag release v2.3.1

---

CHANGES.rst
onadata/__init__.py

Tag release v2.3.2

---

onadata/apps/api/management/commands/delete_users.py
onadata/apps/api/tasks.py
onadata/apps/api/tests/management/commands/test_delete_users.py
onadata/apps/logger/tests/models/test_xform.py

Resolves #1715 
Resolves #1502

Add management command to delete users and tests

---

CHANGES.rst
onadata/__init__.py

Tag release v2.3.3

---

CHANGES.rst
onadata/__init__.py

- Use last name as first name if first name isn't present within the OpenID Connect identification token
- The OpenID Connect functionality(signup, login and logout) works
- Basic functionalities (Ability to upload/delete a form and make submissions)

Tag release v2.3.4

---

onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
onadata/apps/api/viewsets/connect_viewset.py
onadata/apps/api/viewsets/user_profile_viewset.py
onadata/apps/logger/views.py
onadata/libs/serializers/user_profile_serializer.py
onadata/libs/utils/cache_tools.py

Cache user_profile object upon creation or update
Closes #1821

Introduce caching for user profile objects

---

.github/release-drafter.yml

- Add release-drafter configuration
Part-of #1837

Add release-drafter configuration

---

onadata/apps/api/tests/viewsets/test_open_data_viewset.py
onadata/apps/api/viewsets/open_data_viewset.py

Included support for select multiple question types for tableau-onadata intergration
Resolves part of #1777 
None

Include support for select multiple questions for tableau integration

---

CHANGES.rst

- Add #1835 to the Changelog file
- N/A
Closes #1858

Add missing entry to changelog

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/viewsets/project_viewset.py

Fixes https://github.com/onaio/onadata/issues/1875
- Update cache when a project is updated
- Tested locally and added unit tests

Update cache when project is updated

---

CHANGES.rst
onadata/__init__.py

- Fix an issue where project endpoint cache would stay stale on Project Update #1874 
- Add support for email:password login on the main views #1878 
> Able to create a Project
> Able to update a Project(_Updated project should be retrievable immediately after update_)
> Able to upload a form to a project & submit data to it
> Able to delete a form
> Able to login with email:password from the `/accounts/login` endpoint

Tag release v2.3.8

---

CHANGES.rst
onadata/__init__.py

- Fix enketo edit url generation #1887

Tag release v2.4.1

---

onadata/apps/main/views.py

- Update main application `api` view

Main API View updates

---

CHANGES.rst
onadata/__init__.py

- CSV Import: Handle re-importing of select_multiple questions #1852 
- Limit message payload sizes #1893

Tag release v2.4.2 

---

CHANGES.rst
onadata/__init__.py

- Project Viewset: Caching refactor PR #1902 [@DavisRayM]
- Ensure only select_multiple questions are flattened into one column PR #1912 [@DavisRayM]
- Handle replication lag when authenticating with a Bearer Token PR #1922 [@DavisRayM]

Tag release v2.4.3

---

CHANGES.rst
onadata/__init__.py

- Re-set project cache using up-to-date project object #1927

Tag release v2.4.4

---

CHANGES.rst
onadata/__init__.py
requirements/base.pip
requirements/dev.pip

Tag release v2.4.5

---

README.rst

Switch to using travis-ci.com

---

.github/workflows/docker-image-build.yml
docker/onadata-uwsgi/Dockerfile

- Add `django-redis` to the optional packages installed in the docker build

Add django-redis to the optional packages

---

onadata/apps/restservice/signals.py

- Asynchronously call webhooks
- Manual testing
_All webhooks will be called asynchronously_

Change Instance Webhooks to be fully asynchronous

---

CHANGES.rst
onadata/__init__.py

- Change Instance Webhooks to be fully asynchronous #1949

[WIP] Tag release v2.4.7

---

onadata/apps/main/tests/test_process.py

- Mock request to google; the request is made to determine the extension of the attached form. _Another option other than mocking it would be to create a URL that would never go private.... which seems a bit harder to maintain in the long term ?_
- Verified test passes
- The test no longer makes a request to Google... _This may raise issues later on possibly? If their endpoints drastically change... Though I doubt that's likely_
Closes #1955

Fix failing URL upload test

---

.github/workflows/docker-image-build.yml

- Update `optional_packages` build argument

Update docker build action workflow

---

CHANGES.rst
onadata/__init__.py

- Fix failing URL upload test PR #1954
- Add enketo-preview url routed to PreviewXFormListViewSet PR #1953
- Data viewset retrieval optimisations PR #1966
- Update "onadata-uwsgi" docker file PR #1956

Tag Release 2.4.8

---

CHANGES.rst
onadata/__init__.py

- Update submission metrics collection PR #1895
- XForm and Data ViewSet updates PR #1971

Tag Release v2.4.9

---

onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/libs/filters.py
onadata/libs/tests/utils/test_numeric.py
onadata/libs/utils/numeric.py

1996 sanitize input recieved by media endpoint

---

CHANGES.rst
onadata/__init__.py

- Clear cache and refresh user profile on email verification. PR #1970 [@DavisRayM]
- Add timestamp filter for the Messaging Viewset. PR #1973 [@DavisRayM]
- Introduce Tableau v2. PR #1910 [@WinnyTroy]
- Handle TypeError raised when `current_count` value is None. PR #1980 [@DavisRayM]
- Add pagination headers to the paginated DataViewSet response. PR #1977  [@DavisRayM]
- Add support for querying a column with multiple conditions. PR #1981 [@DavisRayM]
- Retrieve user profile using case insensitive username filter. PR #1988 [@DavisRayM]
- validate input fields on put form endpoint requests. PR #1991 [@ivermac]
- Update Tableau Documentation. PR #1989 [@WinnyTroy]
- sanitize input recieved by media endpoint . PR #1997 [@ivermac]

Tag release v2.5.0

---

onadata/apps/logger/models/instance.py

- Avoids cases where the signal is fired before a read replica catches
up to the main database
Closes #1987

Use master database when updating XForm Submission Count

---

CHANGES.rst
onadata/__init__.py

- Use master database when updating an XForms Submission Count PR #2002 [@DavisRayM]
- Lockout users based on specific IPs instead of username PR #1978 [@DavisRayM]
- Add pagination & xml support to the data list endpoint PR #2005 [@DavisRayM]
- Paginate data list responses after a configurable threshold PR #2010 [@DavisRayM]
- Trigger error on url in xform title PR #2007 [@ivermac]
- Check if XForm is a MergedXForm and merge field choices if it is(a MergedXForm) PR #2011 [@FrankApiyo]
- Support query by date_modified field * PR #2009 [@DavisRayM]
- Capture attachment file names whose name exceeds 100 chars PR #2003 [@WinnyTroy]
- Merge select one and select multiple options at MergedXform creation PR #2015 [@FrankApiyo]
- Use language parameter to create exports PR #2014 [@FrankApiyo]
- …

Tag release v2.5.1

---

onadata/libs/renderers/renderers.py

- Return data without modification if data is not a list; _Avoids encapsulating the XML within the `submission-batch` root tag_
- Q/A
- N/A
Closes #

Fix "Different root node name" issue

---

onadata/apps/logger/tests/test_simple_submission.py
onadata/apps/main/tests/test_form_errors.py
onadata/apps/main/tests/test_past_bugs.py
requirements/base.pip
requirements/dev.pip
setup.py

- Bump PyXForm version to v1.4.0
- N/A
- N/A
Closes #1897

Update PyXForm dependency to v1.4.0

---

CHANGES.rst
onadata/__init__.py

Fix "Different root node name" issue #2029
Update PyXForm dependency to v1.4.0
QA
None

Bump to v2.5.2

---

.github/workflows/ecr-image-build.yml

- Add AWS ECR github action
- N/A
- N/A

Add github workflow to build an AWS ECR image

---

.github/workflows/ecr-image-build.yml

- Include `ssh_private_key` build arguement
- Set `release_version` to `versionTag` input if present
- N/A
- N/A

Update AWS ECR Image build workflow

---

.github/workflows/docker-image-build.yml
.github/workflows/ecr-image-build.yml

Add arm64 platform to docker build CI

Publish arm64 Docker Image 

---

CHANGES.rst
onadata/__init__.py

- Add github workflow to build an AWS ECR image #2034 
- Publish arm64 Docker Image #2042 
- Lockout IP Changes #2040

Bump to version 2.5.3

---

requirements/base.pip
requirements/dev.pip
requirements/s3.in
requirements/s3.pip
requirements/ses.in
requirements/ses.pip
setup.py

- Update Django version to >= 2.2.19
- Add `deprecated` package to the application setup.py
- Update requirement files
- N/A
- N/A
Closes #2045

Update Django version to the latest 2.2.* version

---

.github/workflows/ecr-image-build.yml
CHANGES.rst
docker/onadata-uwsgi/Dockerfile
requirements/base.pip
requirements/dev.pip
requirements/s3.in
requirements/ses.in
setup.py

- Add review date. PR #2044 [@WinnyTroy]
- Add support for sort and handle streaming of empty datasets on XML Responses. PR #2039 [@DavisRayM]
- Ensure that the CSV Import status is updated on failed import. PR #2046 [@DavisRayM]
- Update Django version to the latest 2.2.* version. PR #2047 [@DavisRayM]

Tag release v2.5.4

---

onadata/apps/main/tests/test_base.py
onadata/apps/main/tests/test_form_api.py
onadata/apps/viewer/tests/test_parsed_instance.py

- Add debug information that may be used to pinpoint the inaccuracy in some of the tests while running in CI
- N/A
- N/A
Closes #2058

Add more debug information & fix flaky tests

---

.github/workflows/ecr-image-build.yml
Dockerfile
onadata/libs/tests/utils/test_csv_builder.py
onadata/libs/tests/utils/test_export_builder.py
onadata/libs/utils/csv_builder.py
onadata/libs/utils/export_builder.py

- Add `_review_date` column when `include_reviews` is true in exports
- Update tests
- Update Dockerfile & ecr-image-build workflow
- N/A
Closes #2054

Add review date column on data exports

---

docs/messaging.rst

- Move supported `verbs` list to the top of the document
N/A
N/A

Update messaging endpoint documentation

---

onadata/apps/logger/models/xform.py

- Ensure project object is refreshed from master database
N/A
N/A
Closes #1660

Project - XForm shared status sync changes

---

CHANGES.rst
onadata/__init__.py

bump version to v2.5.5

---

docs/data.rst
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/viewsets/data_viewset.py

- Introduce async for bulk submission deletions
Closes #2065

Expose ability to Delete a subset or all submissions from the Data endoint

---

onadata/apps/api/tests/viewsets/test_tableau_viewset.py
onadata/apps/api/tools.py
onadata/apps/api/viewsets/v2/tableau_viewset.py

Include ability to switch out media file names for respective urls for tableau WDC connection
Closes onaio/zebra#6093

Tableau WDC media file urls enhancement

---

.github/workflows/ecr-image-build.yml

- Update `ecr-image-build` workflow
- Manual run
- N/A
Closes #

Switch ECR region to `eu-central-1`

---

CHANGES.rst
onadata/__init__.py

- Expose ability to delete a subset or all submissions from the data endpoint. PR #2076
- Tableau WDC media file urls enhancement. PR #2074
- Add the default authentication classes to the export viewset. PR #2023
- Update requirements. PR #2070
- Check if user is an AnonymousUser before trying to retrieve their project role. PR #2084
- Add optional `flow_title` field to the TextItService. PR #2086
- Update onadata-uwsgi docker file. PR #2087
- Expound on field query param for the data json format and geojson format. PR #2085
- Add `error_message` field to the Export serializer. PR #2094
N/A

Tag release v2.5.6

---

docs/data.rst

- Updates data documentation with instructions on filtering submissions created during specific time periods
Closes onaio/zebra#6297

Update data endpoint documentation

---

CHANGES.rst
onadata/__init__.py

- Update data endpoint documentation PR #2100
- Add service_health view function PR #2097 
- Add CI Test Github Actions workflow PR #2102

Tag v2.5.7

---

onadata/apps/api/tests/viewsets/test_media_viewset.py
onadata/libs/utils/presigned_download_url.py

- Ensure content-disposition header is encoded correctly
- Added tests
- N/A
~- [ ] Updated documentation~
Closes #2106

Ensure content-disposition header is correctly encoded

---

.github/workflows/docker-image-build.yml

- Remove `latest` tag
- Add support for image building when a pull request is merged
An image will be built every time a new pull request is merged to master

Modify docker image build workflow

---

.github/workflows/docker-image-build.yml

- Ensure Github Action workflow has correct syntax
_Fixes an issue with the changes introduced in PR_

Ensure github action workflow has correct syntax

---

CHANGES.rst
onadata/__init__.py

- PR #2098 [@DavisRayM]
- PR #2109 [@DavisRayM]
- PR #2114 [@DavisRayM]
- Replace internal OpenID Connect tools for [ona-oidc](https://github.com/onaio/ona-oidc). PR #2096 [@WinnyTroy]
- PR #2116 [@DavisRayM]
- PR #2122 [@denniswambua]
- PR #2123 [@WinnyTroy]
- PR #2124 [@WinnyTroy]
- PR #2127 [@DavisRayM]

Tag release v2.5.8

---

onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/logger/models/xform.py

- Update regex that validates urls.
- Include check to capture and report when invalid characters are used within the form title value
Closes onaio/zebra#6453

Update validation checks that are run for XForm titles

---

.github/workflows/ci.yml

- Run `sudo apt-get update` to fix the missing package error
N/A
N/A

Fix CI Github action workflow

---

onadata/apps/logger/management/commands/remove_columns_from_briefcase_data.py
onadata/apps/logger/tests/management/commands/test_remove_columns_from_briefcase_data.py

- Add `remove_columns_from_briefcase_data` management command
- Added tests
N/A

Add management command to remove columns from submission XML

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

- Bump `ona-oidc` version from `v0.0.6` to `v0.0.7`

Bump `ona-oidc` version from `v0.0.6` to `v0.0.7`

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

- Bump ona-oidc version to `86d8cd`
- N/A
- N/A

Bump ona-oidc version to `86d8cd`

---

.github/workflows/ecr-image-build.yml

Disable arm builds

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

Bump ona-oidc version

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

- Bump ona-oidc version to `13eb1d`

Bump ona-oidc version to `13eb1d`

---

onadata/libs/serializers/xform_serializer.py

Add `xls_available` field to the XFormSerializer

---

.github/workflows/docker-image-build.yml
.github/workflows/ecr-image-build.yml
requirements/base.in
requirements/base.pip
requirements/dev.pip

Disable caching functionality on the docker build workflows

---

docker/onadata-uwsgi/Dockerfile

- Add `supervisor` to the installed packages

Update `onadata-uwgsi` docker file

---

CHANGES.rst
onadata/__init__.py

- Add `xls_available` field to the XFormSerializer. PR #2174 
- Add management command to create user profiles for accounts that don't have them. PR #2184

Tag release v2.5.14

---

onadata/libs/utils/common_tools.py

- Handle uncaught `StopIteration` exception
Closes #2191

Handle uncaught `StopIteration` exception

---

onadata/apps/logger/management/commands/reapplyperms.py
onadata/libs/permissions.py

- Utilize queryset iterators for permission retrieval
Closes #2187

Utilize queryset iterator for permission retrieval

---

CHANGES.rst
onadata/__init__.py

Tag release v2.5.16

---

CHANGES.rst
onadata/__init__.py

- [Support split select multiples with randomize=true parameters](https://github.com/onaio/onadata/pull/2205)
- [Fix export builder circular import](https://github.com/onaio/onadata/pull/2208)
Closes #

Tag release v2.5.18

---

CHANGES.rst
onadata/__init__.py

- https://github.com/onaio/onadata/pull/2206
Closes #

Tag release v2.5.19

---

docker/onadata-uwsgi/Dockerfile

- Install `uwsgitop` & `django-prometheus`
N/A
N/A

Install `uwsgitop` on the docker builds

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

- Bump `ona-oidc` version to v0.0.10

Bump ona-oidc version to v0.0.10

---

onadata/apps/main/forms.py
onadata/apps/main/tests/test_process.py

- Allow redirects when making a head request on xlsx url upload
Closes #

Fix xlsx url upload

---

extras/reserved_accounts.txt

- Updated reserved usernames list
N/A
N/A

Update reserved usernames list

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.0.1
- Add changelog entry for v3.0.0 and v3.0.1

Tag release v3.0.1

---

onadata/apps/api/viewsets/data_viewset.py
onadata/libs/utils/google.py

- Add additional missing scopes
Closes #

Add additional required google sheets scope

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.0.2
- Add changelog entry for v3.0.2

Tag release v3.0.2

---

onadata/libs/utils/csv_import.py
onadata/libs/utils/export_builder.py

Handle an Attribute exception when `celery.current_task` is None.
Closes #2242

current_task is Instance of task being executed, or None

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Add changelog for v3.0.3
- Bump version to v3.0.3

Tag release v3.0.3

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Add changelog for v3.0.4
- Bump version to v3.0.4

Tag release v3.0.4

---

.github/dependabot.yml
.github/workflows/ecr-image-build.yml

- Add `dependabot.yml` file
- Add additional step to scan docker images and upload results to Github security lab

Add dependabot configuration and trivy scans

---

docker/onadata-uwsgi/Dockerfile
requirements/azure.pip
requirements/base.in
requirements/base.pip
requirements/dev.pip

- Updates Azure dependency files
- Updates ona-oidc version to v1.0.1
- Updates dev.pip to have the latest Django version
N/A
N/A
~- [ ] Included tests~
~- [ ] Updated documentation~
Closes #

Update Azure dependencies

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Tag release v3.2.0

---

docs/data.rst
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/viewsets/data_viewset.py

- Add pagination to geojson response on the data endpoint
- Tests
- None
Closes #2294

Add ability to paginate geojson responses

---

onadata/libs/utils/image_tools.py

Fix aws storage class typo

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Add changelog for v3.3.0
Bump version to v3.3.0

Tag release v3.3.0

---

onadata/libs/utils/image_tools.py

Fix typo while retrieving configurations

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump onadata to v3.3.1

---

.github/workflows/ecr-image-build.yml

- Send Trivy summary to Slack
Closes #

Send Trivy summary to Slack

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Add changelog for v3.3.2
- Bump version to v3.3.2

Tag release v3.3.2

---

onadata/apps/api/tests/viewsets/test_abstract_viewset.py
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/logger/tests/test_briefcase_api.py
onadata/apps/logger/tests/test_briefcase_client.py
onadata/apps/main/tests/test_base.py

Fixes to minimize flaky tests.

Add check number of media files in test

---

README.rst

- Add Github CI Badge
- Remove unused Travis CI badge
- Checked the documentation preview
None

Update CI Badge

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Update change log
- Bump version to v3.3.3

Tag release v3.4.0

---

docs/forms.rst
docs/projects.rst
onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/viewsets/project_viewset.py

- Add pagination to projects endpoint
- Tests
Closes #

Add pagination to projects endpoint

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump to v3.5.0
- Update changelog

Tag release v3.5.0

---

onadata/libs/mixins/cache_control_mixin.py
onadata/settings/common.py

- Add `CacheControlMiddleware` class
- Update `CacheControlMixin` class
- Add `set_cache_control` utility function
- Remove `CACHE_MIXIN_SECONDS` setting
- Add `CACHE_CONTROL_DIRECTIVES` setting
N/A

Support `no-store` cache control value

---

onadata/libs/utils/google.py
onadata/settings/common.py

- Remove scopes that request for too much access on google sheets integration

Remove scopes that are not necessary for the Google Integration

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- bump to v3.6.0
- update change log

Tag release v3.6.0

---

onadata/apps/logger/models/instance.py

- Retry post submission processing on failure to retrieve Instance
Tasks will be retried if an instance object does not exist

Retry post submission processing tasks if submission is not found

---

CHANGES.rst
onadata/__init__.py
setup.cfg

bump to v3.6.1
update change log

Tag release v3.6.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

bump to v3.6.2
update change log

Tag release v3.6.2

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- bump to v3.7.0
- update change log

Tag release v3.7.0

---

onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
onadata/apps/api/tools.py
onadata/apps/api/viewsets/organization_profile_viewset.py
onadata/apps/api/viewsets/project_viewset.py
onadata/apps/main/models/user_profile.py
onadata/libs/models/share_project.py
onadata/libs/serializers/organization_member_serializer.py
onadata/libs/serializers/share_project_serializer.py
onadata/libs/utils/common_tags.py
onadata/libs/utils/project_utils.py

- Ensure organization permissions are propagated
- Ensure Project manager and owners have permissions to edit forms
Closes https://github.com/onaio/zebra/issues/7286

Formbuilder permission propagation changes

---

CHANGES.rst
docker/onadata-uwsgi/Dockerfile
onadata/__init__.py
setup.cfg

- Formbuilder permission changes. PR #2345

Tag release v3.7.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump onadata to v3.8.0
- Update changelog

Tag release v3.8.0

---

onadata/libs/throttle.py

- Add custom throttling class
Closes #

Add custom throttling class that can be used to throttle requests based on request headers

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Tag release v3.8.1

---

.github/workflows/ci.yml
onadata/libs/tests/test_throttle.py
onadata/libs/throttle.py
onadata/settings/common.py

- Remove white space from cached user-agent key, fixes `InvalidCacheKey` exception
- Update CI to use spy to find Ubuntu mirrors
Closes #2368

Remove spaces from user-agent cached key

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Tag release v3.8.2

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump onadata to v3.8.3
- Update changelog

Tag release v3.8.3

---

docs/media.rst
onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/api/tests/viewsets/test_merged_xform_viewset.py
onadata/apps/api/viewsets/dataview_viewset.py
onadata/libs/filters.py

- Ensure attachments endpoint works as expected for Merged datasets and filtered datasets
N/A
closes https://github.com/onaio/onadata/issues/2375
Closes https://github.com/onaio/zebra/issues/7352

Media endpoint DataViews and merged datasets support

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump onadata to v3.8.4
- Update changelog

Tag release v3.8.4

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.8.6
- Update change log

Tag release v3.8.6

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

Update `savreaderwriter` version

---

.github/workflows/ci.yml
.pylintrc
onadata/apps/messaging/serializers.py

- test(debug): capture exception raised
- refactor(messaging): compare module and name instead of functions
- chore(debug): use `report_exception` instead

Fix `IndexError` exception raised when comparing functions

---

docker/onadata-uwsgi/Dockerfile

Bump base image

---

.github/workflows/ci.yml
docker/onadata-uwsgi/Dockerfile

- Switch to an Alpine based image
- Bump Python version to 3.10

Switch to an Alpine based release image

---

docs/index.rst
docs/messaging_stats.rst
onadata/apps/api/tests/viewsets/test_messaging_stats_viewset.py
onadata/apps/api/tests/viewsets/test_ona_api.py
onadata/apps/api/urls/v1_urls.py
onadata/apps/api/viewsets/messaging_stats_viewset.py

- Add `MessagingStatsViewset` class
- Add tests for the messaging stats viewset
N/A

Add statistics endpoint for actstream actions

---

.dockerignore
.github/workflows/ci.yml
.github/workflows/docker-image-build.yml
.github/workflows/ecr-image-build.yml
docker/onadata-uwsgi/Dockerfile
docker/onadata-uwsgi/Dockerfile.alpine
docker/onadata-uwsgi/Dockerfile.ubuntu

Bump action versions

---

onadata/libs/utils/export_builder.py

- Handle `AttributeError` raised for multiple select choice elements
Related to https://sentry.k8s.onalabs.org/organizations/ona/issues/44054/?project=50&query=is%3Aunresolved

Handle `AttributeError` returned when element is None

---

onadata/apps/main/templates/show.html
onadata/apps/main/tests/test_form_show.py
onadata/apps/viewer/tests/test_export_list.py

- Fix exports bug - update to allow xlsx export types instead of xls
- Tests
- Only .xlsx export types should be supported, not .xls
Closes #

Fix xlsx export bug on UI

---

CHANGES.rst
onadata/__init__.py
onadata/libs/tests/test_throttle.py
onadata/libs/throttle.py
setup.cfg

Tag release v3.9.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Tag release v3.9.2

---

requirements/azure.pip
requirements/base.pip
requirements/s3.pip
requirements/ses.pip

- Update sqlparse to v0.4.4
- Remediates https://github.com/onaio/onadata/security/code-scanning/1510

Update sqlparse package

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.10.0
- Add task to permanently delete soft-deleted submissions by @KipSigei in #2446 
- Add ability to permanently delete submissions by @KipSigei in #2437 
- Update pyxform version to v1.12.0 with case management support by @KipSigei  in #2341 
- Update sqlparse package to fix security vulnerability by @KipSigei in #2447

Tag release v3.10.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.10.1
- Optimize performance on attachments endpoint @KipSigei in #2452 
- Update django to v3.2.20 fix security vulnerability by @KipSigei in #2454

Tag release v3.10.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Bump version to v3.12.0
- Add indexes to instance model date fields
`PR #2393  <https://github.com/onaio/onadata/pull/2393>`
[@KipSigei]

Tag release v3.12.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v3.13.1
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2474

Release candidate v3.13.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to 3.14.2
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2489
[@KipSigei]
- https://github.com/onaio/onadata/pull/2486
[@kelvin-muchiri ]

Bump version to v3.14.2

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version 3.14.3
- https://github.com/onaio/onadata/pull/2493
- https://github.com/onaio/onadata/pull/2492

Bump version to 3.14.3

---

onadata/apps/api/tests/viewsets/test_connect_viewset.py
onadata/libs/serializers/user_profile_serializer.py

- Catch error experienced when getting user without auth token and create user token if doesn't exist
- Added test
Closes #2490

Create user auth token if doesn't exist on user get

---

onadata/apps/api/viewsets/briefcase_viewset.py

- Trigger database call to correctly capture OperationalError on briefcase viewset
Closes #

Trigger database call to correctly capture OperationalError

---

onadata/apps/api/viewsets/briefcase_viewset.py

- Check length of paginated instances in briefcase viewset instead of unpaginated instances
Closes #

Check length of paginated instances in briefcase viewset

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py

- Enable token authentication on Form List API
- Tests
- The Form List related endpoints should be able to work with Token authentication
Closes #

Enable Token Authentication on Form List API

---

onadata/libs/utils/image_tools.py

Set AWS credentials when generating pre-signed URLS

---

docker/onadata-uwsgi/Dockerfile.ubuntu
yarn.lock

Update Base Image (Focal)
Update JS dependencies to fix the following vulnerabilities
- https://github.com/onaio/onadata/security/dependabot/39
- https://github.com/onaio/onadata/security/dependabot/42
- https://github.com/onaio/onadata/security/dependabot/38
- https://github.com/onaio/onadata/security/dependabot/46
- https://github.com/onaio/onadata/security/dependabot/45
- https://github.com/onaio/onadata/security/dependabot/44
- https://github.com/onaio/onadata/security/dependabot/40

Security Updates

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v3.19.0
- Upgrade package pricing to v1.1.1

Bump version to v3.19.0

---

docker-compose.yml
docker/onadata-uwsgi/Dockerfile.ubuntu

Fix API docs not created when building image
Closes #

Fix API docs not created when building image

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.1.0
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2589
- https://github.com/onaio/onadata/pull/2587

Bump version to v4.1.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.2.0
**New Features**
- https://github.com/onaio/onadata/pull/2504
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2598
- https://github.com/onaio/onadata/pull/2600
- https://github.com/onaio/onadata/pull/2595
- https://github.com/onaio/onadata/pull/2597
- https://github.com/onaio/onadata/pull/2599

Tag release v4.2.0

---

.github/workflows/ecr-image-build.yml

- Update Metadata action to capture tags, at the moment it only captures branches

Update Metadata action to capture tags

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.2.2
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2608

Tag release v4.2.2

---

docs/messaging.rst

- Add missing documentation for filtering events by timestamp on the messaging endpoint
Closes #2615

Update messaging endpoint docs

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.3.0
**New Features**
- https://github.com/onaio/onadata/pull/2592
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2613
- https://github.com/onaio/onadata/pull/2616
- https://github.com/onaio/onadata/pull/2620

Tag release v4.3.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.3.1
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2621

Bump version to v4.3.1

---

docker/onadata-uwsgi/Dockerfile.ubuntu
requirements/azure.pip
requirements/base.pip
requirements/dev.pip
requirements/docs.pip
requirements/s3.pip
requirements/ses.pip

Address the following vulnerabilities:
- https://github.com/onaio/onadata/security/code-scanning/3233
- https://github.com/onaio/onadata/security/code-scanning/3283
- https://github.com/onaio/onadata/security/code-scanning/3240
Closes #

Security updates 27/06/2024

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.3.2
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2624
- https://github.com/onaio/onadata/pull/2627

Tag release v4.3.2

---

onadata/apps/logger/migrations/0019_alter_project_options_and_more.py

Tune performance for adding `add_project_entitylist` permission to existing owners and managers

Tune migration performance

---

docs/entities.md
docs/projects.rst
onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/libs/serializers/project_serializer.py

Add Entity related data to forms on project retrieve endpoint
Update Entities docs
Closes #2638

Add Entity related data to forms on project retrieve endpoint

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.3.3
- https://github.com/onaio/onadata/pull/2631
- https://github.com/onaio/onadata/pull/2630
- https://github.com/onaio/onadata/pull/2632
- https://github.com/onaio/onadata/pull/2629
- https://github.com/onaio/onadata/pull/2635
- https://github.com/onaio/onadata/pull/2639
**Bug Fixes**
- https://github.com/onaio/onadata/pull/2618

Tag release v4.3.3

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/logger/models/instance.py
onadata/apps/logger/tasks.py
onadata/apps/logger/tests/test_tasks.py
onadata/libs/utils/cache_tools.py

- Update the project `date_modified` field in batches periodically
Closes #

Optimize updates to project `date_modified` field when submitting data

---

onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/viewsets/xform_list_viewset.py
onadata/apps/main/models/meta_data.py
onadata/apps/main/tests/test_metadata.py
onadata/libs/renderers/renderers.py
onadata/libs/utils/cache_tools.py

Cache XForm manifest data 
Faster retrieval of XForm manifest

Cache XForm manifest data

---

docs/entities.md
onadata/apps/api/tests/viewsets/test_dataview_viewset.py
onadata/apps/api/tests/viewsets/test_entity_list_viewset.py
onadata/apps/api/urls/tests/test_v2_urls.py
onadata/apps/api/viewsets/entity_list_viewset.py
onadata/apps/logger/tasks.py
onadata/libs/serializers/entity_serializer.py
onadata/libs/utils/logger_tools.py

Add ability to delete Entities in bulk

Add ability to delete Entities in bulk

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.4.0
- https://github.com/onaio/onadata/pull/2662
- https://github.com/onaio/onadata/pull/2660
- https://github.com/onaio/onadata/pull/2659
- https://github.com/onaio/onadata/pull/2657
**Bug fixes**
- https://github.com/onaio/onadata/pull/2661

Bump version to v4.4.0

---

onadata/apps/main/urls.py

Add ability to have configurable Django admin path

Add ability to have configurable Django admin path

---

onadata/apps/logger/migrations/0023_populate_project_entity_list_perm.py

Fix exception thrown when running migration

Fix argument of type 'ProjectUserObjectPermission' is not iterable

---

onadata/apps/api/viewsets/xform_list_viewset.py
onadata/apps/api/viewsets/xform_submission_viewset.py

Add throttle scopes for xform_list and xform_submission viewsets

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.5.1
- https://github.com/onaio/onadata/pull/2685

Bump version to v4.5.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.5.2
- https://github.com/onaio/onadata/pull/2689

Bump version to v4.5.2

---

onadata/apps/api/viewsets/project_viewset.py
onadata/libs/utils/common_tools.py

- Add logging to project view
local testing
N/A

Add logging to project view page: add why we get 400 in log

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.7.0
**Features**
- https://github.com/onaio/onadata/pull/2683
- https://github.com/onaio/onadata/pull/2699
- https://github.com/onaio/onadata/pull/2696
- https://github.com/onaio/onadata/pull/2694
- https://github.com/onaio/onadata/pull/2688
- https://github.com/onaio/onadata/pull/2651

Bump version to v4.7.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.7.1
**Ehancements**
- https://github.com/onaio/onadata/pull/2701

Bump version to v4.7.1

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

https://github.com/onaio/ona-oidc/releases/tag/v1.1.1

Update ona-oidc version to 1.1.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.9.0
**Bug fixes**
- https://github.com/onaio/onadata/pull/2710
- https://github.com/onaio/onadata/pull/2717
- https://github.com/onaio/onadata/pull/2715
- https://github.com/onaio/onadata/pull/2713
- https://github.com/onaio/onadata/pull/2712

Bump version to v4.9.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.9.1
**Bug fixes**
- https://github.com/onaio/onadata/pull/2727
- https://github.com/onaio/onadata/pull/2721

Bump version to v4.9.1

---

README.rst
pre-commit.sh

Update pre commit install instructions

Update pre commit install instructions

---

onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/api_export_tools.py

- Fix GeoJSON export exports bug
- Added a test case 
- N/A
Closes #2735

Ensure geojson exports creation process is idempotent

---

docs/management.rst
onadata/apps/logger/admin.py
onadata/apps/logger/management/commands/restore_form.py
onadata/apps/logger/models/data_view.py
onadata/apps/logger/models/xform.py
onadata/apps/logger/tests/models/test_data_view.py
onadata/apps/logger/tests/models/test_xform.py
onadata/apps/main/models/meta_data.py
onadata/apps/main/tests/test_metadata.py

Add ability to restore soft deleted form via management command
Add ability to restore soft deleted from on Django admin
Soft delete XForm if delete is triggered on Django admin
Closes #

Add management command to restore soft deleted form

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.10.1
**Bug fixes**
- https://github.com/onaio/onadata/pull/2754
**Security updates**
- https://github.com/onaio/onadata/pull/2750

Bump version to v4.10.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.11.0
**Bug fixes**
- https://github.com/onaio/onadata/pull/2757
- https://github.com/onaio/onadata/pull/2755

Bump version to v4.11.0

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.11.2
**Bug fixes**
- https://github.com/onaio/onadata/pull/2763
- https://github.com/onaio/onadata/pull/2764
- https://github.com/onaio/onadata/pull/2766

Bump version to v4.11.2

---

onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/viewsets/project_viewset.py

Ensure projects are returned in the reverse order of creation

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v4.12.0
- https://github.com/onaio/onadata/pull/2768
- https://github.com/onaio/onadata/pull/2762
**Bug fixes**
- https://github.com/onaio/onadata/pull/2770

Bump version to v4.12.0

---

onadata/apps/main/models/meta_data.py
onadata/apps/viewer/models/data_dictionary.py
onadata/libs/tests/utils/test_logger_tools.py
onadata/libs/utils/logger_tools.py

Fix new columns not showing in CSV after replacing form
New columns show up in CSV after replacing form
Closes #

Fix new columns not showing in CSV after replacing form

---

onadata/apps/logger/management/commands/add_project_entitylist_perm.py

Add a new mgt command that applies entitylist perms

---

CHANGES.rst
onadata/__init__.py
setup.cfg

* Fix new columns not showing in CSV after replacing form by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2779
* Add a new mgt command that applies entitylist perms by @FrankApiyo in https://github.com/onaio/onadata/pull/2785

chore: Bump onadata version v4.14.0

---

onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/model_tools.py

Adds a check for "instance" attributes on survey elements.
Added a test
N/A
Closes https://github.com/onaio/onadata/issues/2795

fix: Ensure survey element has the "instance" attribute

---

onadata/apps/api/tests/viewsets/test_abstract_viewset.py
onadata/apps/api/tests/viewsets/test_attachment_viewset.py
onadata/apps/logger/fixtures/test_forms/survey_names/instances/survey_names_2012-08-17_11-24-53.xml
onadata/apps/logger/tests/test_briefcase_api.py
onadata/apps/logger/tests/test_briefcase_client.py
onadata/apps/logger/tests/test_simple_submission.py
onadata/apps/main/tests/test_base.py
onadata/libs/serializers/merged_xform_serializer.py
onadata/libs/utils/logger_tools.py

- Check submission duplicate using only instanceID uuid

feat(perf): Check submission duplicate using only instanceID uuid

---

.github/workflows/ci.yml
docker-compose.yml
docs/metadata.rst
onadata/apps/api/tests/viewsets/test_attachment_viewset.py
onadata/apps/api/tests/viewsets/test_data_viewset.py
onadata/apps/api/tests/viewsets/test_export_viewset.py
onadata/apps/api/tests/viewsets/test_media_viewset.py
onadata/apps/api/tests/viewsets/test_metadata_viewset.py
onadata/apps/api/tests/viewsets/test_project_viewset.py
onadata/apps/api/tests/viewsets/test_team_viewset.py
onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
onadata/apps/api/tests/viewsets/test_xform_viewset.py
onadata/apps/api/tools.py
onadata/apps/api/urls/v1_urls.py
onadata/apps/api/viewsets/xform_viewset.py
onadata/apps/logger/models/xform.py
onadata/libs/models/share_project.py
onadata/libs/models/share_team_project.py
onadata/libs/models/share_xform.py
onadata/libs/permissions.py
onadata/libs/serializers/metadata_serializer.py

- Add new can view and can view minor roles
Added test cases
**Todo**

Add new can view and can view minor roles

---

onadata/libs/kms/tools.py
onadata/libs/tests/kms/test_tools.py

Invalidate organization cache after creating, rotating, disabling key

---

.github/workflows/ci.yml
onadata/apps/logger/tests/test_encrypted_submissions.py
onadata/libs/serializers/data_serializer.py

Fix 404 eror on project submission endpoint

---

onadata/libs/kms/tools.py
onadata/libs/templates/organization/key_rotated.html
onadata/libs/tests/kms/test_tools.py

Send email notification after rotating key

Send email notification after rotating key

---

CHANGES.rst
docker/onadata-uwsgi/Dockerfile.ubuntu
onadata/__init__.py
setup.cfg

- Update to use a new debian image from April
- Version bump
- 
Closes #

Base image updates 0525 and version bump to v5.0.4

---

onadata/apps/logger/models/xform.py
onadata/libs/tests/kms/test_tools.py
onadata/libs/tests/utils/test_export_tools.py
onadata/libs/utils/export_tools.py

Exclude deleted attachments when generating attachments zip

Exclude deleted attachments when generating attachments zip

---

onadata/libs/kms/tools.py
onadata/libs/tests/kms/test_tools.py

Creating encryption key KMS alias
Update encryption key KMS encryption

Create key alias

---

onadata/libs/kms/clients.py
onadata/libs/tests/kms/test_clients.py
onadata/libs/utils/cache_tools.py

Save KMSAPIClient token to avoid unnecessary re-authentication by different processes

Save KMSAPIClient token to avoid unnecessary re-authentication

---

onadata/apps/logger/tasks.py
onadata/apps/logger/tests/test_tasks.py
onadata/libs/kms/tools.py
onadata/libs/templates/organization/key_grace_expiry_reminder.html
onadata/libs/tests/kms/test_tools.py

Add ability to send grace period expiry reminder

Send grace period expiry reminder

---

onadata/apps/logger/management/commands/create_org_key.py
onadata/apps/logger/management/commands/tests/test_create_org_key.py

Add management command to create organizations' encryption keys

Add management command to create organizations' encryption keys

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version v5.1.0
**Features**
- https://github.com/onaio/onadata/pull/2789

Bump version to v5.1.0

---

.dockerignore
docker/onadata-uwsgi/Dockerfile.ubuntu

Only copy the final documentation build and files required in the final build

Reduce final Docker image size

---

CHANGES.rst
onadata/__init__.py
setup.cfg

Bump version to v5.2.1
- https://github.com/onaio/onadata/pull/2870
- https://github.com/onaio/onadata/pull/2867

Bump version to v5.2.1

---

CHANGES.rst
onadata/__init__.py
setup.cfg

- Update Dockerfile
`PR #2891 <https://github.com/onaio/onadata/pull/2891>`
[@FrankApiyo]

Bump onadata version to v5.3.1

---

onadata/apps/api/tests/viewsets/test_tableau_viewset.py
onadata/apps/api/viewsets/v2/tableau_viewset.py

Fix Mismatch between tableau schema and data if repeat section is within group section
None
Closes #2893

fix: resolve mismatch between tableau schema and data if repeat section is within group section

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

Bump valigetta from v0.1.0 to v0.2.1 to resolve uncaught incorrect padding error

fix: bump valigetta to v0.2.1 to resolve uncaught incorrect padding error

---

requirements/base.in
requirements/base.pip
requirements/dev.pip

Bump oidc to v2.4.0 to add ability to import user

feat: bump oidc to v2.4.0 to add ability to import user

---

.gitignore
onadata/apps/api/management/commands/export_inactive_users_orgs.py
onadata/apps/api/tests/management/commands/test_export_inactive_users_orgs.py
onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
onadata/apps/logger/tests/test_briefcase_client.py
onadata/libs/utils/inactive_export_tracker.py
setup.cfg

Inactive users
