onaio/onadata

- docs/submissions.rst
The `Form ID` in the documentation is actually the `id_string` and that tripped us up quite a bit during dev.
> Small docs fix on Form ID

- docs/projects.rst
- onadata/apps/api/management/commands/reassign_permission.py
- onadata/apps/api/tests/models/test_team.py
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/logger/models/project.py
- onadata/apps/logger/models/xform.py
- onadata/apps/viewer/models/parsed_instance.py
- onadata/libs/permissions.py
closes #811
New roles added
- ``dataentry-only`` Role for a user able to submit data only
- ``dataentry-minor`` Role for a user able to submit and view only data he/she submitted
- ``editor-minor`` Role for a user able to view and edit data he/she submitted
> xform metadata perms

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/viewer/models/export.py
- onadata/libs/utils/export_tools.py
> include export options in outdated export function

- onadata/apps/logger/models/attachment.py
- onadata/apps/logger/templates/downloadSubmission.xml
- onadata/apps/logger/tests/models/test_attachment.py
- onadata/apps/viewer/tests/test_attachment_url.py
- onadata/apps/viewer/views.py
- Filename uses original filename on the `/view/downloadSubmission` briefcase api endpoint
- support for serving attachment files directly with no redirect to s3
closes #853
> ODK Briefcase downloadSubmission endpoint should use the original filename

- docs/index.rst
- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/api/viewsets/xform_list_viewset.py
- onadata/apps/main/urls.py
- onadata/apps/main/views.py
- onadata/libs/utils/viewer_tools.py
> Retrieve username from request object and not xform object

- docs/projects.rst
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/project_serializer.py
- onadata/libs/tests/serializers/test_project_serializer.py
List the collaborators when the projects endpoint is filtered by owner.
For example: `/api/v1/projects?owner=<username>` could have among it's users non-owners i.e collaborators
```
{...
"projectid": 5
"users": [{...}
{"user": "sluggie"
"role":   "readonly"}
{...}]
...}
```
Compared to `api/v1/projects/<project-id>` which will not list collaborators.
closes #869
> Add share users to users when projects filtered by username

- onadata/libs/utils/csv_builder.py
> catch the assert error

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/main/models/user_profile.py
- onadata/settings/common.py
> Grant new users formbuilder perms

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
The dataviews endpoint should not require auth for public dataviews, 
`api/v1/dataviews/<public-dataview-id>`, filtered by the dataview id but should require auth for a request for all dataviews, `api/v1/dataviews`.
closes #891
> Dataviews endpoint should not require auth for public dataviews.

- docs/profiles.rst
Currently the docs are a little confusing right here https://api.ona.io/static/docs/profiles.html#register-a-new-user, which led me to try figure out the issue for a while. It's just a missing underscore.
> firstname to first_name in docs for required sign up fields

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/logger/models/project.py
- onadata/libs/permissions.py
- onadata/libs/utils/project_utils.py
Org members permissions are added to the project and transitively the xform.
However, this doesn't happen for org *teams* which has admins as the initial team (teams[0]) and every other element in teams. 
This adds the admins/owners team permissions to the xform permission.
> Add organization teams permissions to xform.

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tools.py
- onadata/apps/logger/models/project.py
- onadata/libs/models/share_project.py
- onadata/libs/serializers/organization_member_serializer.py
Adding a person as an admin to an org should add them as an owner in all all org projects and removing them from the org should remove them as owners in all org projects.
closes #924
> Add org admins as owners in all projects

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/viewer/tasks.py
- onadata/libs/tests/utils/test_async_status.py
- onadata/libs/utils/api_export_tools.py
- onadata/libs/utils/async_status.py
- onadata/libs/utils/csv_builder.py
- onadata/libs/utils/export_builder.py
- onadata/libs/utils/export_tools.py
> export task progress

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/libs/serializers/xform_serializer.py
- onadata/libs/utils/project_utils.py
Catching `XLSFormError` exception and raising `ParseError` allows rest-framework to return a response with `status_code` 400 instead of failing with a `500` `status_code`.
Fixes #953
> Handle XLSFormError exceptions on form parial_update

- onadata/apps/api/tools.py
- onadata/apps/viewer/models/data_dictionary.py
- onadata/libs/utils/project_utils.py
Reduce time in adding forms to projects by performing permission assignment in async tasks.
> Set xform permissions async.

- onadata/libs/data/query.py
- onadata/libs/tests/utils/test_chart_tools.py
This should also stop the random failures test_chart_tools test on travis
> Order charts by the group by field(s)

- .style.yapf
- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/logger_tools.py
- onadata/settings/common.py
> Proper submission count on CSV imports

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/apps/logger/tests/test_publish_xls.py
- onadata/apps/main/views.py
- onadata/apps/viewer/tasks.py
- onadata/libs/exceptions.py
- onadata/libs/serializers/xform_serializer.py
- onadata/libs/utils/common_tools.py
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/logger_tools.py
- onadata/libs/utils/project_utils.py
- onadata/libs/utils/viewer_tools.py
Fixes: #1072
We discovered that the API endpoint to get an enketo edit url
encountered >400 level errors it did not properly set the HTTP
status code and instead returned the edit url as false.
This set of commits fixes that by raising an EnketoError exception
which has a friendly default error message that can be overridden.
> Ensure that >400 level HTTP errors are properly handled

- onadata/apps/logger/models/instance.py
- onadata/apps/logger/models/note.py
- onadata/apps/logger/tests/models/test_note.py
Fixes: #1069
We now return an empty string in place of created_by when a Note is not
linked to any user.
> Check for and handle cases where created_by is None for a Note object

- .gitignore
- onadata/apps/viewer/tasks.py
- onadata/apps/viewer/tests/test_tasks.py
- onadata/settings/common.py
Fixes: #1068
Create periodic tasks which:
- Find old pending exports and mark them as failed.
- Find old failed exports and delete them
The 'oldness' is determined by a configurable setting.
> Cancel or delete stale pending and failed exports

- onadata/apps/viewer/tests/test_export_builder.py
- onadata/libs/utils/export_builder.py
Fix #1087
Ensure that all multiple choice answers in split columns are displayed as
numeric values i.e. 0 or 1
> Fix SAV Exports For select_multiple With Choice Filters

- onadata/libs/utils/viewer_tools.py
Make sure that this function always returns a URL as expected, or raises an
exception.
Fix: #1099
> Code Cleanup To Improve The enketo_url Function

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/fields/json_field.py
- onadata/libs/serializers/project_serializer.py
Validate metadata field on Project Serializer to reject invalid
inputs/values.
Additionally, ensure that metadata is always converted to valid JSON for
storage.
Fix: #977
> Validate metadata Field on Project Serializer

- onadata/apps/viewer/tests/test_export_builder.py
- onadata/libs/utils/common_tags.py
- onadata/libs/utils/export_builder.py
Prevent the export builder from failing when data from a form with
multiple choices that have duplicate names by ignoring all but one of the
choices that have a duplicated names.
Fix: #983
> Prevent SAV Exports From Failing When Choices Lists Have Duplicate Names

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/libs/filters.py
Add the ability to filter data endpoints using Instance model fields.
Done through a django-filter FilterSet. Implement filters for the
following fields:
- version
- date_created
- date_modified
- status
- submitted_by
- user
- uuid
Fix: #1048
> Add Instance Model Fields As Data Endpoints Filters

- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/api/viewsets/xform_list_viewset.py
- onadata/libs/filters.py
- xform_pk if not existing to respond with 404
- apply all filters to queryset whether a user is authenticated or not.
> formList with xform_pk fixes

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/libs/data/query.py
- onadata/libs/tests/utils/test_chart_tools.py
- onadata/libs/utils/chart_tools.py
- Applies when a non numeric is being grouped by more than one field.
- Also, adds COUNT aggregate to group_by queries.
> Support grouping on non numeric field.

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/libs/serializers/data_serializer.py
Handles the exception
```python
AttributeError: 'NoneType' object has no attribute 'read'
```
It used to be handled by https://github.com/onaio/onadata/commit/2615055be40481da08d73d346f0592228ba2c4ea#diff-edf7b0b4bd8a5b8676bf0c6c7badabd4L150, but after the refactor it is best handled in the validate phase of the `SubmissionSerializer`.
> Validate presence of the xml_submission_file

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/api/viewsets/xform_submission_viewset.py
- Add tests for HEAD requests to submission endpoint.
> Return correct response for HEAD requests on submission endpoint

- docs/forms.rst
Update docs to mention which question types in FLOIP Ona supports.
Partially closes https://github.com/onaio/onadata/issues/1175
> Specify supported FLOIP types in Ona

- onadata/apps/logger/models/xform.py
- onadata/libs/tests/utils/test_csv_builder.py
- onadata/libs/utils/csv_builder.py
> Do not split select multiple in repeats if False

- onadata/apps/api/tests/viewsets/test_osm_viewset.py
- onadata/libs/utils/osm.py
Use nexted transaction.atomic() blocks when doing new queries inside
save_osm_data so that a TransactionManagementError is not raised, especially
in cases where we catch an IntegrityError
Fix: #1202
> Ensure that save_osm_data does not raise TransactionManagementError

- onadata/apps/viewer/tasks.py
Remove code that defines periodic tasks so that it can be made configurable
Fix: #1220 
Related: https://github.com/onaio/playbooks/pull/672
> Remove periodic task scheduling

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/settings/common.py
Use file size because it represents a better estimate of how long
processing the file would take than simply counting the number of
rows in the csv.
Set default file size threshold at 100kB loosely based on:
https://www.postgresql.org/message-id/4D2F2C71.8080805%40dndg.it
Fix: #1224
> Use File Size to Determine Whether To Do csv_import Asynchronously

- onadata/apps/viewer/tests/test_export_builder.py
- onadata/apps/viewer/tests/test_tasks.py
- onadata/libs/utils/export_builder.py
- onadata/libs/utils/export_tools.py
Add a test to ascertain that SAV exports fail when the form has duplicate column names.
Fix: #1216
> KJ | JW: Test That SAV Exports With Duplicate Column Names Fail

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/logger/models/instance.py
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/export_builder.py
- onadata/libs/utils/logger_tools.py
- Added 'name' to attachment
- Edited function that returns attachment uri to replace
spaces with underscores
> Display Links To Images With Spaces In Filenames Correctly

- onadata/apps/viewer/tests/test_export_builder.py
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/export_builder.py
- Get correct value labels for select questions with the same name across different SAV sections.
- Ensure that we do not attempt to handle duplicate fields that appear across SAV sections.  They are not an issue because they represent different SPSS 'sheets'.
Fix: #1226
> Deal With Duplicate Fields in Different SAV Sections

- onadata/apps/api/tests/fixtures/flow-results-missing-resource-name.json
- onadata/apps/api/tests/fixtures/flow-results-number-question-names.json
- onadata/apps/api/tests/viewsets/test_floip_viewset.py
- onadata/libs/serializers/floip_serializer.py
- onadata/libs/utils/logger_tools.py
Ensures we only return 400 error - raising `serializer.ValidationError` ensures that on form publishing any errors that occur are reported to the user in a manner they can understand and address.
> Floip handle publishing exceptions

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/api/viewsets/open_data_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/apps/main/views.py
- onadata/apps/viewer/static/js/data_view.js
- onadata/libs/mixins/total_header_mixin.py
- onadata/libs/utils/common_tools.py
> 1188 remove x total

- onadata/libs/tests/utils/test_csv_builder.py
- Remove check that the columns are the same
- Add check for BOM at the beginning of the file
- This is because Python2 adds the BOM before every column header while Python3 adds it only once
in the beginning of the file
Fix #1341 
More information:
https://github.com/jdunck/python-unicodecsv/blob/master/unicodecsv/py2.py
https://github.com/jdunck/python-unicodecsv/blob/master/unicodecsv/py3.py
https://docs.python.org/3/howto/unicode.html#reading-and-writing-unicode-data
https://tobywf.com/2017/08/unicode-csv-excel/
> Check BOM In Beginning of Export File

- onadata/libs/tests/utils/test_chart_tools.py
This test initially assumed that the English language will always be index 1 which is not the case. So instead of passing in the value 1, get the actual language index from the field label.
Fix #1359
> Pass In Correct Language Index

- onadata/apps/messaging/README.md
- onadata/apps/messaging/backends/mqtt.py
- onadata/apps/messaging/tests/test_backends_mqtt.py
Make sure the messaging app can send messages to secure MQTT servers.
> Add TLS support to messaging

- onadata/libs/tests/utils/test_export_tools.py
Add assert statement to confirm that deleted osm content is not shown in generated export
Fix #776
> Confirm that deleted osm data does not exist in export

- onadata/apps/messaging/backends/mqtt.py
- onadata/apps/messaging/tests/test_backends_mqtt.py
XForm objects dont have a `name` attribute, they have a `title`.
> Fix get XForm messaging metadata

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/parsed_instance_tools.py
- Add test to check filter by submission time using different date formats
- Add date format to parsed instance tools
Fix #1293
> Add Date Format

- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/models/attachment.py
- onadata/apps/logger/tests/models/test_attachment.py
- onadata/apps/logger/tests/test_briefcase_api.py
- onadata/apps/logger/tests/test_importing_database.py
- onadata/apps/main/tests/fixtures/transportation/view/downloadSubmission.xml
- onadata/libs/tests/utils/test_export_builder.py
- Store attachments in a form specific folder
Fix #961
> Change upload to location for attachments

- docs/profiles.rst
- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/serializers/monthly_submissions_serializer.py
- Add new endpoint that returns the total number of submissions to a user's private and public forms
- Add monthly submissions serializer
- Add tests
> New Monthly Submissions Endpoint

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/serializers/user_profile_serializer.py
- onadata/libs/tests/serializers/test_user_profile_serializer.py
Once a user changes his/her password, track the last time this edit is done.
> Track password edit

- onadata/apps/api/tests/viewsets/test_merged_xform_viewset.py
- onadata/libs/serializers/merged_xform_serializer.py
This should allow the user to see what the problem with the merged form is.
Fix #1153
> Raise ValidationError on PyXFormError exceptions

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/serializers/user_profile_serializer.py
- onadata/libs/tests/serializers/test_user_profile_serializer.py
This reverts commit aced16c870ecd72bf714704bf1c14d568e976f48, reversing
changes made to a5b4303a9f3f5e79ce5363bb477c0b8c178943f0.
This changes result in the exception posted on issue
https://github.com/onaio/onadata/issues/1467. There is need to rethink
how the functionality should be implemented.
> Revert "Merge pull request #1456 from onaio/track_password_edit"

- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/logger_tools.py
Loop through instances instead of using queryset.first() method which
seems to be expensive because of the order_by id that it adds to the
query. This was observed on a table with millions of records on a
very fresh database, PostgreSQL selectect an IndexScan in the query
which was taking quite a long time execute and increased the number
of queries waiting to be processed.
> Add get_first_record() function.

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/serializers/user_profile_serializer.py
- onadata/libs/tests/serializers/test_user_profile_serializer.py
Introduce last_password_edit field in the metadata json field
Upon creation of an account add the last_password_edit time
Upon password change update last_password_edit
fixes #1454 
fixes #1467
> Track password edits:

- onadata/libs/authentication.py
fixes #1500 
Default TEMP_TOKEN_EXPIRY_TIME of 6 hours, incase there's no DEFAULT_TEMP_TOKEN_EXPIRY_TIME
> Default TEMP_TOKEN_EXPIRY_TIME

- onadata/apps/logger/models/xform.py
- onadata/apps/logger/tests/models/test_xform.py
Only take the first 100 characters of id_string and sms_id_string as per max_length set for field.
fixes #1430
> Fix error on deleting xform with long id_string or sms_id_string

- onadata/libs/serializers/fields/instance_related_field.py
- onadata/libs/serializers/fields/project_related_field.py
- onadata/libs/serializers/fields/utils.py
- onadata/libs/serializers/fields/xform_related_field.py
This prevents running a query against the xform object which will
include all fields and for forms whose XML is at least 1MB it can dump
more than 5GB of data into memory resulting in processess being killed,
especially where a form has more than 5 metadata objects.
> Use content_type to determin metadata content_object type

- onadata/libs/tests/utils/test_csv_builder.py
- onadata/libs/utils/csv_builder.py
Only do duplication validation to keys in ordered columns. 
Open validation creates extra columns.
fixes #1408
> Fix extra columns in multiple select exports

- onadata/libs/templates/registration/verification_email.txt
Remove link validity duration on email message.
Links no longer expire after a day
fixes #1489
> Remove link expiration message on verification email

- onadata/libs/serializers/xform_serializer.py
- onadata/libs/tests/serializers/test_xform_serializer.py
Only generate hash for linked datasets, not on any other form media files uploaded
fixes #1411
> Only generate hash for linked datasets

- onadata/apps/api/tests/viewsets/test_merged_xform_viewset.py
- onadata/apps/logger/models/xform.py
Return `0` instead of `None` for `'num_of_submissions'` where the parent is deleted. 
fixes #1511
> 1511 fix merged dataset deleted parent

- onadata/apps/logger/models/project.py
- onadata/apps/logger/models/xform.py
Ensure that no project forms are left undeleted when the project is deleted. Fixes https://github.com/onaio/onadata/issues/1494
> WRAP PROJECT AND FORMS SOFT_DELETE IN TRANSACTION.ATOMIC

- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/export_tools.py
Filter media attachments zip export based on the query parameters given.
fixes #1028
> Filter media attachments exports

- onadata/apps/api/viewsets/xform_viewset.py
- onadata/settings/common.py
The `file.content_type` might not be a true representation of what the file is. 
When mime_type is not provided from the browser, the resulting `content_type` is not always correct. Hence the move to use the file extension instead
> Use file extension instead of mimetype.

- onadata/apps/api/tests/fixtures/formList.xml
- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/main/tests/test_process.py
- onadata/libs/renderers/renderers.py
Optional fields in formList such as manifestUrl should not be included in formList incase none exists.
fixes #1519
> Optional manifest url

- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/csv_import.py
Get rid of extra `uuid` tag that get's appended to all instanceID rows. This extra tag made old instances be considered new instances.
fixes #1540
> Fix failing csv bulk edits

- onadata/libs/tests/utils/test_viewer_tools.py
- onadata/libs/utils/viewer_tools.py
- onadata/settings/common.py
Limit the size of the zip exports to avoid machines running out of space due to huge reports.
> Limit the size of zip exports.

- CHANGES.rst
- onadata/__init__.py
- onadata/libs/serializers/widget_serializer.py
Widgets endpoint fail when .json is appended to the url and the format not specified
Here we get the format from kwargs or default to json
> Pick passed format or default to json in GenericRelatedField serializer

- docs/forms.rst
- onadata/apps/api/tests/mocked_data.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/libs/tests/utils/test_viewer_tools.py
- onadata/libs/utils/viewer_tools.py
- onadata/settings/docker.py
- onadata/settings/travis_test.py
- requirements/base.pip
- requirements/dev.pip
- setup.py
This PR contains the functionality to expose Enketo's single submission url.
> Exposes submissions url to enketo

- onadata/libs/tests/utils/test_export_builder.py
Was supposed to address #1483. But it was fixed on pyxform side by [this ](https://github.com/XLSForm/pyxform/pull/235). 
This has an additional test for show_choice_labels=true in exports. Labels to be used in the exports instead of names when this parameter is set to true.
Fixes #1483
> Exports with label choices test.

- onadata/libs/tests/utils/test_viewer_tools.py
- onadata/libs/utils/viewer_tools.py
- onadata/settings/common.py
This is an improvement to #1556 which fixes #1370.
The size of exports is limited to `ZIP_REPORT_ATTACHMENT_LIMMIT` which is currently set to 500mb
> Limit ZIP Exports Size

- onadata/libs/tests/utils/fixtures/date.csv
- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/common_tags.py
- onadata/libs/utils/csv_import.py
Excel sometimes reformats the date to `mm/dd/YYYY HH:MM` which is not in line with how we store datetime.
This addresses the conversion of the excel datetime to a string format that's consistent with Onadata and ODK.
fixes #1577 
> Handle excel datetime in CSV Import

- onadata/libs/renderers/renderers.py
These custom renderers render content perfectly when the response is the expected data but fail when there are errors in the response.
Here, the errors are handled, the unicode response is encoded to str.
fixes #1598
> Handle errors in custom renderers

- onadata/apps/logger/views.py
- onadata/apps/sms_support/parser.py
- onadata/libs/authentication.py
- onadata/libs/serializers/stats_serializer.py
- onadata/libs/serializers/xform_serializer.py
- script/i18ntool.py
In python 3, the Exceptions don't have the attribute message. It's been replaced by args. The Exception by itself is a string, and that's what I have decided to use as is.
fixes #1606
> Remove message attribute from Exceptions

- onadata/libs/serializers/password_reset_serializer.py
- onadata/libs/tests/serializers/test_password_reset_serializer.py
In python3, when a binary string is rendered to string, the ascii code representation of `b'` and `'` characters are used.
Here we specifically use the decoded strings to avoid errors caused by the above.
fixes #1610
> Use strings instead of binary strings in reset_url generation

- onadata/apps/viewer/models/parsed_instance.py
- onadata/libs/utils/logger_tools.py
I can't find the use of this argument in this save function.
It throws errors aswell when included.
fixes #1615
> Get rid of _async keyword on Parsed Instance save() method.

- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/export_builder.py
This function `encode_if_str` is used in Google Export aswell. Converting all items to string is a functionality only applicable to sav. In google export, this function leads to problems when data supposed to be sent as raw is sent as a string.
Will fix [this](https://github.com/onaio/google-export/issues/89) google-export issue
> Only convert to string sav_writer values in `encode_if_str`

- onadata/libs/serializers/submission_review_serializer.py
- onadata/libs/tests/serializers/test_submission_review_serializer.py
In the previous implementation, the post request either had to include a note string or have the the note completely not included in the payload and therefore, having a blank note i.e `"note":""` failed.
Here, empty notes are permitted for APPROVED and PENDING statuses.
More details [here](https://www.django-rest-framework.org/community/3.0-announcement/#the-required-allow_null-allow_blank-and-default-arguments)
fixes #1623 
> Allow blank notes in reviewing Approved/Pending submissions

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/libs/authentication.py
- onadata/libs/templates/account_lockout/lockout_email_subject.txt
- onadata/libs/templates/account_lockout/lockout_end.txt
- onadata/libs/templates/account_lockout/lockout_start.txt
- onadata/libs/utils/cache_tools.py
- onadata/libs/utils/email.py
- onadata/settings/common.py
- onadata/settings/travis_test.py
Track the login attempts using MemCache.
Lockout user if the limit is reached.
Send email upon lockout and end of the lockout.
Addresses [this](https://github.com/onaio/playbooks/issues/1298).
> Limit login attempts

- onadata/apps/logger/models/widget.py
- onadata/apps/viewer/views.py
- onadata/libs/utils/model_tools.py
Removes ```generate_uuid_for_form``` since its simiilar in functionality and syntax to  ```get_uuid```.  
closes #1638
> Remove duplicate function that generates uuid

- onadata/apps/api/tools.py
- onadata/apps/api/viewsets/organization_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/apps/messaging/backends/base.py
- onadata/apps/restservice/viewsets/restservices_viewset.py
Replaces custom load_class function with a Django utility function import_string that has the same functionality with a more comprehensive error handling and reporting scheme
closes: #1636
> Depracate load_class in favour of Django's import_string

- docs/submission_review.rst
- onadata/apps/api/tests/viewsets/test_submission_review_viewset.py
- onadata/apps/api/viewsets/submission_review_viewset.py
- onadata/libs/tests/serializers/test_submission_review_serializer.py
Bulk creation of reviews was only implemented and tested at the serializer but not at the Viewset.
This PR addresses this with a custom create function to handle bulk creation of submission reviews.
fixes #1623
Signed-off-by: lincmba <lincolncmba@gmail.com>
> Bulk creation of submission reviews

- docs/media.rst
- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/apps/api/viewsets/attachment_viewset.py
> Add count parameter to media endpoint

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/utils/cache_tools.py
Check if the user is locked out when changing password.
Tracks the number of attempts made to a maximum limit of 10.
Locks out user when maximum limit is reached.
> Limit change password attempts

- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/libs/serializers/password_reset_serializer.py
Fixes playbooks#1410
Introduces the user email during token generation.
This would invalidate the token when the user updates their email.
> Override django inbuilt password reset token generation

- onadata/apps/api/tasks.py
- onadata/libs/authentication.py
- onadata/libs/tests/utils/test_email.py
- onadata/libs/utils/email.py
>  Manually strip newlines from email headers when sending user verification emails

- onadata/apps/viewer/tasks.py
The returned HTTP404 Response object exception has no view for any kind of interactions.
> Removing get_object_or_404 query on a task

- onadata/apps/api/tests/viewsets/test_submission_review_viewset.py
- onadata/libs/serializers/submission_review_serializer.py
Bulk submission reviews of status approved without a note/comment contain a null value for the note field.
This PR resolves scenerios when this occurs to resultantly create bulk submission reviews of status Approved.
> Bulk submission review no note

- onadata/libs/serializers/merged_xform_serializer.py
- onadata/libs/tests/serializers/test_merged_xform_serializer.py
Fixes onaio/zebra#5683
Newly created merged-datasets have bind attributes that contain relevance fields references to fields that were removed when generating the merged datasets. 
This PR seeks to drop/ignore the relevant column coming from the bind attributes of child elements in the newly created merged-datasets.
> Clean elements of bind attributes when creating merged datasets

- onadata/apps/api/tests/models/test_organization_profile.py
- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/tools.py
- onadata/libs/serializers/user_profile_serializer.py
During registration of a new account profile, a new instance of the user model, `Django’s django.contrib.auth.models.User` is created to represent the new account, with the is_active field set to False. 
This occurs in the Registration Profile model.
Onadata validates the username, email and twitter field provided during the creation of a user registration profile against the auth User model.
This PR seeks to catch the IntegrityError exception and return a proper message to the user if the exception is triggered during creation of a user profile. Resolves #936
> Validate auth user username before creating Registration Profile

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/models/parsed_instance.py
- onadata/apps/viewer/tests/test_parsed_instance.py
Form level permission restrictions were failing upon searching the data.
This PR addresses this issue.
fixes #1692
Signed-off-by: lincmba <lincolncmba@gmail.com>
> Fix form level permission restrictions on search

- onadata/apps/api/tests/viewsets/test_floip_viewset.py
- onadata/apps/api/viewsets/floip_viewset.py
This PR modifies the `/api/v1/flow-results/packages/[form_uuid]/responses` endpoints response in order to adhere to the [flow results specification](https://floip.gitbooks.io/flow-results-specification/content/api-specification.html#publish-responses-to-a-package)
Fixes #1690
> Modify Flow Results Response Endpoint Formatting

- onadata/apps/api/storage.py
- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/apps/api/viewsets/connect_viewset.py
Fix an issue where multiple ODKTokens would be returned when more that one token existed at the time of regeneration.
> Fix Multi ODK Token return on regeneration

- docs/projects.rst
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/viewsets/project_viewset.py
- onadata/libs/serializers/share_project_serializer.py
- onadata/libs/tests/serializers/test_share_project_serializer.py
Enable permissions to be added to multiple users when sharing a project by passing in a list of comma separated usernames
- Allow the `/api/v1/project/{pk}/share` endpoint to accept CSV values on the `username` param. 
Changed payload sample:
```
{
username: "some_user,another_user",
role: "change_form",
}
```
Closes #1700
> Add the ability to share projects to multiple users

- onadata/apps/api/tests/models/test_organization_profile.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tools.py
- onadata/libs/serializers/organization_serializer.py
- Return members of the 'Owners' team on the `/orgs` endpoint under the `users` key.
> Return owner team members on the Organization endpoint

- onadata/libs/serializers/share_project_serializer.py
- onadata/libs/tests/serializers/test_share_project_serializer.py
When a user tries to share a project with multiple users by passing in CSV data with space inbetween the usernames an error is returned The following user(s) does not exist: someuser even though the user does.
This error is caused by spacing in between the data (userone, someuser). This PR fixes the error by stripping the spaces from the username before sharing a project.
Closes #1722
> Handle spaces passed within the CSV usernames while sharing projects

- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/libs/filters.py
This PR currently allows logged in users to be able to get forms belonging to user accounts that have require authentication set to false from the XForm list viewset.
Fixes: #1753
> Allow logged in users(non anonymous users) to view forms in accounts that have require_authentication set to False

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/viewsets/project_viewset.py
Added a filter to the queryset in ProjectViewset to ensure that we do not return projects associated with inactive organizations
Ran onadata locally and ensured that only projects associated with active organizations are gotten from the projects endpoint
Fixes: #1732
> Change queryset in project viewset in order to return only projects associated to active organizations.

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_openid_connect_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/api/viewsets/briefcase_viewset.py
- onadata/apps/api/viewsets/openid_connect_viewset.py
- onadata/apps/logger/views.py
- onadata/libs/utils/logger_tools.py
- Query usernames case-insensitively
- Properly validated usernames when creating users through OpenID Connect
- Add test to make sure case doesn't matter when making submissions to `/<username/submission`
Closes #1761
> Change submission endpoint to be case-insensitive when matching usernames

- onadata/apps/api/management/commands/set_api_permissions.py
- onadata/apps/api/models/organization_profile.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tools.py
- onadata/libs/serializers/organization_member_serializer.py
- Add `OwnerRole` permissions to creator for `OrganizationalProfile.userprofile_ptr`
- Remove `Role` permissions from a user when they are removed from an organization
- Added a test to verify that the change works
- In order for these changes to take effect for all existing organizations the `set_api_permissions` management command needs to be run
Issue #1754 is being caused because the `User` object returned through `User.objects.get` and `get_object_or_404` links to a `UserProfile` and not a `OrganizationProfile` when `user.profile` is called. The user / creator in this case normally doesn't have the OwnerRole / `can_add_xform` attached to the `UserProfile` / `org.userprofile_ptr`.
The `UserProfile` is present due to how django handles model inheritances(more info on that …
> Assign Owner permission to creator for organization account UserProfile

- onadata/settings/common.py
Set the x-frame-options header. Guide from django's documentation [here](https://docs.djangoproject.com/en/3.0/ref/clickjacking/#setting-x-frame-options-for-all-responses)
Fixes #1767
> Add X-Frame-Options Middleware class.

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/libs/utils/logger_tools.py
- Handle `BadStatusLine` error raised when _"a server responds with a HTTP status code that we don’t understand."_
*N/A*
Closes #1759
> Handle error thrown by urllib

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/parsed_instance_tools.py
- Modify '$or' operator. Enable the operator to accept null values
```
/api/v1/data/<form_id>?start=0&limit=100&query={"$or": [{"_review_status":"1", "_review_status": null}]}
```
- Added tests to verify the filter option works
_None so far_
Closes #1743
> Modify '$or' operator

- .travis.yml
- onadata/apps/api/tests/views/test_user_permissions.py
- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/apps/api/tests/viewsets/test_open_data_viewset.py
- onadata/libs/serializers/password_reset_serializer.py
- onadata/libs/tests/serializers/test_password_reset_serializer.py
- requirements/base.pip
- setup.py
- Upgraded the Django version to 2.2
- Tested locally
- Tested on travis
- Full QA may need to be done. In case something bypassed our tests.
Closes #1769
> Upgrade to Django 2.2

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- Track users who initiate asynchronous deletion of XForms
- None
Closes #1797
> Set deleted_by field when deleting XForms asynchronously

- docs/profiles.rst
- docs/user.rst
- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/connect_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/serializers/password_reset_serializer.py
- onadata/libs/utils/user_auth.py
- Invalidate a users api and temporary token when they're password
changes.
- Add test to verify that the api and temporary tokens are renewed
- Added tests
Pending:
- Add new tests
- API Tokens will now need to be re-retrieved when one changes their password
Closes #1782
> Invalidate tokens on password change

- onadata/apps/viewer/tests/test_exports.py
- onadata/libs/utils/export_tools.py
Metadata details for extenal exports are being fetched from the replica database. This may fail if the record may still not be available in read replica.
Fixes #1758
> use_master when fetching external export metadata information

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/api/viewsets/xform_submission_viewset.py
- onadata/libs/serializers/data_serializer.py
- Added `BaseRapidProSubmissionSerializer`
- Added `RapidProJSONSubmissionSerializer`
- Added Tests
- n/a
Closes #1805
> Add support for RapidPro JSON webhook post requests

- onadata/libs/tests/utils/test_export_builder.py
- onadata/libs/utils/export_builder.py
- Handle variable names with curly braces before creating sav exports
- Added test
Closes #1803
> Handle dynamic choice names while generating SAV export

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Refactor to remove `.update()` since it doesn't call  the Instance model's. `save()` method
- `.update()` method doesn't send `post_save` signal required by google exports or any other micro service
Closes #
> Refactor submission deletion queryset

- onadata/apps/logger/management/commands/recover_deleted_attachments.py
- onadata/apps/logger/tests/management/commands/test_recover_deleted_attachments.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/common_tags.py
- Add `file` to `KNOWN_MEDIA_TYPES`
- Update `test_replaced_attachments_not_tracked` test
- Add test for `recover_deleted_attachments` management function
Closes #1815
> Fix issue where file uploads were automatically soft deleted

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/tools.py
- onadata/apps/api/viewsets/dataview_viewset.py
- onadata/apps/api/viewsets/project_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/apps/logger/models/data_view.py
- onadata/apps/logger/models/xform.py
- onadata/libs/models/share_project.py
- onadata/libs/serializers/project_serializer.py
- onadata/libs/tests/serializers/test_project_serializer.py
- onadata/libs/utils/cache_tools.py
- Fixes the issue where making a GET to the projects endpoint immediately after creating a project throws a 404 because the replica db isn't updated with the newly created project on time.
- Tests
- This change will also affect caching project forms, dataviews(filtered datasets) and users
Closes https://github.com/onaio/zebra/issues/5911
> Fix caching issues with newly created projects

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/libs/serializers/data_serializer.py
> Update Enketo kwargs arguments

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/logger/tests/test_digest_authentication.py
- onadata/libs/utils/logger_tools.py
- Modify the get_xform_from_submission function
Closes #1801
> Fix an issue caused when a user tries to submit to a copy of a shared form

- onadata/apps/api/tests/viewsets/test_open_data_viewset.py
- onadata/apps/api/viewsets/open_data_viewset.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/utils/cache_tools.py
- onadata/libs/utils/common_tags.py
- onadata/libs/utils/logger_tools.py
This approach aims to ensure that the column header fields used to create tableau dashboards match the row header fields
Steps taken
- Removed metadata field from both the column headers and row headers
- Include column fields not present in the submission data
- Flatten repeat data in the submission data.
> OpenData endpoint updates

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/project_serializer.py
- onadata/libs/serializers/xform_serializer.py
- onadata/settings/common.py
- Added new `ALLOW_PUBLIC_DATASETS` settings
- Added ability to disable creation of public projects and forms
> Add ability to disable creation of public projects and xforms

- onadata/apps/api/tests/viewsets/test_openid_connect_viewset.py
- onadata/apps/api/viewsets/openid_connect_viewset.py
- During the Open ID Connect authentication process use the last name as the first name if not retrieved from token
> Use last name as first name if first name isn't sent

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/settings/common.py
Add `__enketo_meta_username` cookie with the same value as the `enketo_meta_uid` cookie
Closes #1832
> Add enketo_meta_usename cookie

- CHANGES.rst
- onadata/__init__.py
- Introduced caching for UserProfile objects. PR #1823
- Send CRUD notifications for Forms, Submissions and SubmissionReviews. PR #1793
- Set enketo cookie `__enketo_meta_username` on login PR #1834
- Basic functionality ( Form Upload, Submissions & Exports )
- User functionality ( Able to create a user, update, login & logout ) #1823
- Presence of `__enketo_meta_username` cookie after login #1834
- Form and Submission notifications #1793
> Tag release v2.3.5

- onadata/apps/api/management/commands/delete_users.py
- onadata/apps/api/tasks.py
- onadata/apps/api/tests/management/commands/test_delete_users.py
Included deletion suffix to email associated with the user account
Included cron task to periodically perform task after 30 days
Closes #1843
> Delete User Functionality Updates

- CHANGES.rst
- onadata/__init__.py
- Return FLOIP data for Merged Datasets #1773,  _Introduces a new [migration](https://github.com/onaio/onadata/blob/master/onadata/apps/logger/migrations/0061_auto_20200713_0814.py) on the `logger` app_
- Add deletion suffix to a Users email upon soft deletion #1844 
- Add more flexible MQTT Topics #1850 
- Able to retrieve FLOIP responses & packages for XForms and MergedDatasets(_as well as anything else that should be returned from the endpoint_)
- Able to upload, update, delete and retrieve forms & projects
- Able to submit data to forms via Enketo and ODK Collect
- Able to create a user profile
> Tag release v2.3.6

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/logger/management/commands/replace_form_id_root_node.py
- onadata/apps/logger/tests/management/commands/test_replace_form_id_root_node.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/utils/logger_tools.py
- Set the root node to `data`. _By default the root node of an XForm is always set to `data` unless specifically set to [something else](https://xlsform.org/en/#specify-xforms-root-node-name)_
- Make change backward compatible with forms that have the root node name set to something else other than the default(`data`)
- Add management command that helps replace the XForm ID String as the root node for Instances
Submissions made using RapidPro before the changes in this PR are in effect, will still have the `different root node name` issue. Suggestion: Those submissions should be updated manually on a case by case basis(_Server wide submission XML edits seem a bit too unsafe_)
> Set root node for created submissions to the XForms configured root node

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_submission_review_viewset.py
- Require Admin or Manager privileges in order to perform create, update & delete operations on `SubmissionReview` model.
- Editors will no longer be able to create, update or delete Submission Review objects
Closes #1866
> Ensure user is either an Admin or Manager before allowing submission reviews

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/utils/common_tools.py
- onadata/libs/utils/logger_tools.py
- Set `instanceID` in submission XML when creating
- Updated test
- N/A
Without the `instanceID` in the XML, Enketo generates a new instanceID which instead of editing the original it creates another one. Setting the `instanceID` ensures that the correct submission is edited.
Closes #1868
> Fix duplicate records after edit

- CHANGES.rst
- onadata/__init__.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/utils/common_tools.py
- onadata/libs/utils/logger_tools.py
- Add a way to elongate `ODKToken` expiry data * PR #1847 [@DavisRayM]
- Set the correct root node for created submissions PR #1853 [@DavisRayM]
- Ensure only XForm admins & managers can review submissions PR #1864 [@DavisRayM]
- Update changelogs
- Bump version to v2.3.7
> Tag release v2.3.7

- onadata/apps/main/backends.py
- onadata/apps/main/tests/test_http_auth.py
- Add support for using email in place of username when authenticating through the Non-API views
- Added tests
Closes #1789
> Add support for login with email/password on the classic login pages

- onadata/apps/main/urls.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/tests/utils/test_analytics.py
- onadata/libs/utils/analytics.py
- onadata/libs/utils/common_tags.py
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/logger_tools.py
- requirements/base.pip
- requirements/dev.pip
- setup.py
Based on #1871 
- analytics module to track events
> Initial support for tracking submissions with Segment

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/organization_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/authentication.py
- onadata/libs/serializers/user_profile_serializer.py
- onadata/libs/utils/cache_tools.py
Closes https://github.com/onaio/onadata/issues/1879
- Add caching; ensure it's updated and busted correctly for the UserProfile and OrganizationProfile viewsets
- Update tests
> Add caching to the organization profile viewset

- onadata/apps/api/tests/mocked_data.py
- onadata/apps/api/tests/views/test_user_permissions.py
- onadata/apps/api/tests/viewsets/test_abstract_viewset.py
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/apps/logger/views.py
- onadata/apps/main/management/commands/create_enketo_express_urls.py
- onadata/apps/main/management/commands/update_enketo_urls.py
- onadata/apps/main/models/meta_data.py
- onadata/apps/main/tests/test_form_enter_data.py
- onadata/apps/main/tests/test_form_show.py
- onadata/apps/main/views.py
- onadata/libs/serializers/xform_serializer.py
- onadata/libs/tests/utils/test_viewer_tools.py
- onadata/libs/utils/cache_tools.py
- onadata/libs/utils/viewer_tools.py
- onadata/settings/common.py
- onadata/settings/docker.py
- onadata/settings/travis_test.py
I. The single_submission_url should be present in the response returned by /api/v1/forms/<form_id>/enketo
II. Should be able to retrieve the single_submission_url using /api/v1/forms/<form_id>/enketo?survey_type=single
III. Allow submissions collection from this single Enketo URL
None
Closes #1855
> Enketo endpoint updates

- onadata/apps/api/tests/viewsets/test_open_data_viewset.py
- onadata/apps/api/viewsets/open_data_viewset.py
None
Closes #1877 
Closes #1777
> Tableau unpack gps data into altitude, precision, latitude and longitude columns

- CHANGES.rst
- onadata/__init__.py
- onadata/apps/api/viewsets/open_data_viewset.py
- onadata/libs/tests/utils/test_analytics.py
- onadata/libs/utils/analytics.py
- onadata/libs/utils/common_tags.py
- Initial support for tracking submissions with Segment. PR #1872
- Add caching to the organization profile viewset. PR #1876
- Include support for repeat groups in the Tableau-Onadata integration. PR #1845
- Enketo integration updates. PR #1857 
- Unpack GPS data into separate columns for altitude, precision, latitude, and longitude. PR #1880
> Tag release v2.4.0

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Use `instance_id` and `instance_xml` when generating edit url
- Update tests
- QA
- N/A
> Fix generation of enketo edit urls

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/libs/renderers/renderers.py
- onadata/libs/tests/utils/fixtures/extra_details.csv
- onadata/libs/tests/utils/fixtures/single_submission_extra_details.csv
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/dict_tools.py
- Handle cases where extra details are added on an extra column.
- Flatten split select_multiple questions into one column
- Possible loss of data? _Chance that the `string` value passed in the `select_multiple` field is actually useful? Should we store the data in the metadata ?_
Seems the issue documented in #1655 occurs when a user adds in a column(matching a `select_multiple` question) for extra information. i.e When using a form such as [this](https://docs.google.com/spreadsheets/d/1vu8rN8BCfgK0Dm1NvAp_8Gd66Ux_HbPhXs5K16qN7FU/edit?usp=sharing) and trying to import this kind of [data](https://docs.google.com/spreadsheets/d/1U1wZriv5pJBxCiB_rnCT6ZP5sD27X2fVS2yrjqkiBvU/edit?usp=sharing)
Closes #1655
> CSV Import: Handle re-importing of select_multiple questions

- onadata/apps/messaging/serializers.py
- onadata/apps/messaging/tests/test_utils.py
- Limit the number of IDs present in a message payload; Chunk huge message payloads.
- Added tests
- Notifications with a lot of affected IDs will now be split into chunks. Consumers of the notifications may need to take this into account.
Closes #1892
> Limit message payload sizes

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/tools.py
- onadata/apps/api/viewsets/project_viewset.py
- onadata/apps/logger/models/instance.py
- onadata/apps/logger/models/xform.py
- onadata/libs/tests/utils/test_cache_tools.py
- onadata/libs/utils/cache_tools.py
- Fix an issue where the `num_datasets` value of a project was not updated when a form that used to belong to that form is transferred
- Add `reset_project_cache` utility function
- Re-sets project cache immediately after a new form is uploaded to a project
- Clears project cache on Instance & XForm creation
- Added / Updated tests
- Projects will have their caches re-set immediately after a form is uploaded
- Projects cache will be cleared on XForm save & delete actions as well as on Instance save
Closes #1903
> Project Viewset: Caching refactor

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/libs/tests/utils/fixtures/extra_details.csv
- onadata/libs/tests/utils/fixtures/single_submission_extra_details.csv
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/dict_tools.py
- Check to see if a question is a select multiple before flattening
- Added tests
- N/A
Closes #1906
> Ensure only select_multiple questions are flattened into one column

- onadata/apps/api/viewsets/connect_viewset.py
- onadata/libs/authentication.py
- onadata/libs/tests/test_authentication.py
- onadata/settings/common.py
- Add `MasterReplicaOAuth2Validator` class
- Configure `MasterReplicaOAuth2Validator` as the OAuth2 Request validator
- Retrieve `UserProfile` from main database on failure
- Added tests
- On failure to retrieve the `AccessToken` from the read replica, the application will now try to retrieve the `AccessToken` from the master database.
Closes #1920
> Handle replication lag when authenticating with a Bearer Token

- onadata/apps/api/tools.py
- Retrieve project object from the master database
N/A
> Re-set project cache using up to date project object

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/project_serializer.py
- Added test
- Grant the owners and members of an organization permissions on project transfer
- Added tests
- N/A
Closes #1886
> Ensure project permissions are upgraded on project transfer

- onadata/settings/common.py
- requirements/base.pip
- requirements/dev.pip
- setup.py
#Changes / Features implemented
- Downgrade celery requirement. _Celery 5 is still not stable enough for us to move to it_
Partially reverts #1905
> Downgrade celery requirement

- .github/workflows/docker-image-build.yml
- docker/onadata-uwsgi/Dockerfile
- docker/onadata-uwsgi/docker-compose.yml
- Add `docker-image-build.yml` github workflow
- Update docker file; Add an intermediate container to install optional dependencies
- Built an image
> Dockerfile updates

- .github/workflows/docker-image-build.yml
- CHANGES.rst
- onadata/__init__.py
- Ensure project permissions are upgraded on project transfer PR #1932
- Check submission encryption status before Instance creation PR #1938
- Downgrade celery requirement PR #1942
- Dockerfile updates PR #1937
> Tag v2.4.6 release

- onadata/apps/api/viewsets/data_viewset.py
- onadata/libs/pagination.py
- Introduced new `SUBMISSION_RETRIEVAL_THRESHOLD` setting
- Disable Queryset ordering after an XForms' submission count surpasses the `SUBMISSION_RETRIEVAL_THRESHOLD` setting
- Disable ETag functionality after an XForms' submission count surpasses the `SUBMISSION_RETRIEVAL_THRESHOLD` setting
- Add `CountOverridablePaginator` and `CountOverridablePageNumberPagination`
- Switch the default pagination class for the Data viewset to `CountOverridablePageNumberPagination`
- Set a limit on the number of records that can be returned at one time when pagination is not used; _Separate PR... Will most likely break 3rd Party applications that rely on this functionality_
- N/A
- After a certain threshold data retrieval (even via pagination) is not ordered and the ETag functionality is disabled
> Data viewset retrieval optimisations

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/logger/models/instance.py
- onadata/apps/logger/models/xform.py
- onadata/libs/pagination.py
- onadata/libs/serializers/xform_serializer.py
- onadata/libs/utils/cache_tools.py
- Utilize stored `num_of_submissions` value instead of recalculating the value when User requests `XForm`
- Add ability to configure `max_page_size`
- Retry pagination when an `OperationalError` is raised
- Update documentation on the `page` and `page_size` query parameters
- Modify how `submission_count_for_today` is tracked/calculated
- Added Tests
Closes #
> XForm and Data ViewSet updates

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- Refresh user profile from database before updating metadata
- Clear user-profiles cache on email verification
- N/A
- N/A
Possible fix for #1948
> Clear cache and refresh user profile on email verification

- onadata/apps/api/tests/viewsets/test_ona_api.py
- onadata/apps/api/urls.py
- onadata/apps/main/urls.py
- onadata/apps/messaging/filters.py
- onadata/apps/messaging/tests/test_messaging_viewset.py
- onadata/apps/messaging/viewsets.py
- Add `timestamp` as a filter
- Added Tests
- N/A
Closes #1870
> Add timestamp filter for the Messaging ViewSet

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/logger/models/instance.py
- Handle TypeError raised when `current_count` value is None
- Updated Tests
- N/A
Solves: 
https://sentry.onalabs.org/ona/onadata/issues/86687/?query=is%3Aunresolved
> Handle TypeError raised when `current_count` value is None

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_tableau_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Implement a `Link` header to track page information & relations on the paginated DataViewSet response
- Update test
- Update documentation
- N/A
Closes #1969
> Add pagination headers to the paginated DataViewSet response

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/parsed_instance_tools.py
- Added support for multiple query conditions on the same column
- Added Test
- N/A
Closes #1979
> Add support for querying a column with multiple conditions

- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/api/viewsets/xform_list_viewset.py
- Retrieve user profile using case insensitive username filter
- Added test
All requests made to `<username>/formList` will now search for the `user` via a case-insensitive search using the username.
Closes #1982
> Retrieve user profile using case insensitive username filter

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/models/xform.py
Validate form version and sanitize form description
Added checks in a test to validate form versions don't have invalid characters and ensure form description with html tag characters are sanitized
Closes #1990
Fixed has been inspired by https://devstringx-technologies.medium.com/html-injection-f1c9fc713d51
> 1990 validate input fields on put form endpoint requests

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/libs/renderers/renderers.py
- onadata/libs/serializers/data_serializer.py
- requirements/base.pip
- requirements/dev.pip
- setup.py
- Add `InstanceXMLRenderer` class
- Add `DataInstanceXMLSerializer` class
- Add support for XML rendering & pagination on the `/api/v1/data` endpoint
**Pending**:
Closes #2000
> Add pagination & xml support to the data list endpoint

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Paginate responses when requested data is more than the retrieval threshold
- Added tests
Closes #2008
> Paginate data list responses after a configurable threshold 

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/libs/utils/chart_tools.py
- Added a test case
Closes #2013
> Check if XForm is a MergedXForm and merge field choices if it is(a MergedXForm)

- onadata/apps/logger/xform_instance_parser.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/logger_tools.py
- Include check to confirm attachment file name length before saving submission
- Added Tests
Closes #1939
> Capture attachment file names whose name exceeds 100 chars

- onadata/libs/serializers/merged_xform_serializer.py
- onadata/libs/tests/serializers/test_merged_xform_serializer.py
- onadata/libs/utils/chart_tools.py
Closes #2016
- Revert changes made [here](https://github.com/onaio/onadata/pull/2011) and instead merge `select one` and `select multiple` options at MergedXform creation(in the serializer). This is better because it would work for all the endpoints that make use of these options (not only the charts endpoint)
**NB**: Earlier added tests for the charts endpoints and all existing test should still pass
> Merge select one and select multiple options at MergedXform creation

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/apps/logger/migrations/0062_auto_20210202_0248.py
- onadata/libs/utils/chart_tools.py
- Set `xform` data key to the XForm ID when no `accepted_format` is given
- When no accepted format is given the return `xform` value shall be the ID
> Fix Charts endpoint JSON response not rendering

- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/libs/authentication.py
- Lockout IP from a specific account
- Manual testing
- Clients will now only be locked out from a specific account instead of the entire system
> Lockout IP Changes

- onadata/apps/logger/models/instance.py
- onadata/apps/logger/tests/models/test_instance.py
- onadata/apps/viewer/models/parsed_instance.py
- onadata/libs/utils/common_tags.py
- requirements/base.pip
Adds submission review dates to data endpoint response
Updated tests
QA
Closes #2037
> 2037 add review date

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/viewer/models/parsed_instance.py
- onadata/apps/viewer/parsed_instance_tools.py
- onadata/apps/viewer/tests/test_parsed_instance.py
- onadata/libs/models/sorting.py
- onadata/libs/renderers/renderers.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/tests/utils/test_sorting.py
- Handle streaming empty datasets using XML Renderer
- Add `_date_modified` to the NONE_JSON_FIELD list
- Sort none & filter none JSON fields using the model field
- Added tests
- N/A
Closes #2000
> Add support for sort and handle streaming of empty datasets on XML Responses

- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/csv_import.py
- Return failed import async status on exception
- Reset XForm submission count on failed import
- Test that on failed import a response is returned
- Added tests
- N/A
Closes #2036
> Ensure that the CSV Import status is updated on failed import

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
> Ignore accepted renderer & media type for the export async endpoint

- .github/workflows/ecr-image-build.yml
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/logger/tests/models/test_instance.py
- onadata/apps/main/tests/test_form_api.py
- Pass an Instance ID instead of an Instance object to `send_message`
- Update test to ensure call arguments are correct
- N/A
Closes #2056
> Fix submission deletion endpoint error

- .travis.yml
- onadata/apps/api/tests/viewsets/test_media_viewset.py
- onadata/apps/api/viewsets/media_viewset.py
- onadata/libs/utils/presigned_download_url.py
- Generate image URLs that contain content-disposition whether locally or in s3 bucket
Closes #
> Generate pre-signed URLs with content disposition

- docs/index.rst
- docs/messaging.rst
- Add documentation for the messaging viewset
N/A
N/A
I've tagged the documentation as WIP since the `project` and `user` target types are currently not utilized on the application; There is currently no message sent for those target types
Closes #2063
> Add documentation for the messaging endpoint

- .travis.yml
- docs/messaging.rst
- onadata/apps/main/tests/test_form_api.py
- onadata/apps/messaging/backends/mqtt.py
- onadata/apps/messaging/tests/test_backends_mqtt.py
- onadata/apps/messaging/tests/test_messaging_viewset.py
- onadata/apps/messaging/tests/test_signals.py
- onadata/apps/messaging/tests/test_tasks.py
- onadata/apps/messaging/viewsets.py
- onadata/libs/pagination.py
- onadata/libs/tests/test_pagination.py
- Add pagination for the messaging endpoint. Added `page` and `page_size` query params
- Add message retrieval limit
- Add `Link` header to paginated responses
- Add `generate_pagination_headers` utility function
- Add/Updated tests
The messaging viewset will now not return all the messages that are currently available if the number of messages surpasses the retrieval threshold.
Closes #2064
> Add pagination for the messaging endpoint

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/project_serializer.py
- Test that project owners are able to see a list of all the users their project has been shared too
Users with manager or owner level permissions will now be able to view all the users the project has been shared to
Closes #2069
> Ensure project owners are able to view all their collaborators from the project list

- onadata/apps/logger/models/instance.py
- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/csv_import.py
- onadata/libs/utils/logger_tools.py
- Update `safe_create_instance` function. _Add new argument `instance_status`_
- Set instance status to `imported_via_csv` for CSV Imported submissions
- Updated questions
- N/A
Closes #1983
> Set status to `imported_via_csv` for CSV Imported submissions

- onadata/apps/main/models/meta_data.py
- onadata/libs/serializers/metadata_serializer.py
- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/common_tags.py
- onadata/libs/utils/csv_import.py
- Save request users username in `Instance` metadata
- Add `IMPORTED_VIA_CSV_BY` common tag
- Modify `safe_create_instance` function; Add `instance_status` arguement
- Added tests
N/A
Closes #1984
> Track users who initiate CSV imports

- onadata/apps/api/tests/viewsets/test_export_viewset.py
- onadata/apps/api/viewsets/export_viewset.py
- Add the default authentication classes to the Export viewset
N/A
Closes #2024
> Add the default authentication classes to the Export viewset

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/libs/serializers/project_serializer.py
- Test that anonymous users are able to list all public projects
- Check if the user is an anonymous user before retrieving their project role
- N/A
Closes #2082
> Check if user is an AnonymousUser before trying to retrieve their project role

- docs/restservices.rst
- onadata/apps/main/models/meta_data.py
- onadata/apps/restservice/tests/viewsets/test_restservicesviewset.py
- onadata/libs/models/textit_service.py
- onadata/libs/serializers/textit_serializer.py
- onadata/libs/utils/common_tags.py
- Add optional `flow_title` field
- Update tests & documentation
- Update tests
- N/A
Closes #2075
> Add optional `flow_title` field to the TextItService

- docker/onadata-uwsgi/Dockerfile
- Ensure github public key is in the known hosts
- Local testing
- N/A
Closes #2088
> Update onadata-uwsgi docker file

- docs/data.rst
- Updated documentation
Closes #2052
> Expound on field query param for the data json format and geojson format

- docs/forms.rst
- onadata/apps/api/tests/viewsets/test_export_viewset.py
- onadata/libs/serializers/export_serializer.py
- onadata/libs/tests/serializers/test_export_serializer.py
- Add `error_message` field to the export serializer
- Add test
- Update documentation
- Added tests
- N/A
Closes #1936
> Add `error_message` field to the Export serializer

- onadata/apps/api/management/commands/retrieve_org_or_project_list.py
- onadata/apps/api/tests/management/commands/test_retrieve_org_or_project_list.py
- onadata/libs/utils/organization_utils.py
- onadata/libs/utils/project_utils.py
- Add `retrieve_org_or_project_list` management command & tests
- Added tests
N/A
Closes #2051
> Add `retrieve_org_or_project_list` management command

- onadata/apps/api/tests/viewsets/test_openid_connect_viewset.py
- onadata/apps/api/viewsets/openid_connect_viewset.py
- onadata/libs/utils/openid_connect_tools.py
- Retrieve `first_name` & `last_name` from `name` claim if present
- Retrieve `code` value from either `POST` data or query params
- Added tests
N/A
Closes #2110
> Open ID - Add `name` claim splitting functionality

- .github/workflows/docker-image-build.yml
- Use `GITHUB_REF` instead of `GITHUB`
> Use the `GITHUB_REF` environment variable instead of `GITHUB`

- .github/workflows/docker-image-build.yml
- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/libs/serializers/data_serializer.py
- Add non-list metadata fields to the XML attributes
- Update test to ensure the attributes are present
Included tests
N/A
This PR makes changes to the API Responses expected on the data endpoint `/api/v1/data/<id>.xml`. The following is the new structure suggested in this PR:
```
<submission-batch>
<submission-item submissionData="" dateCreated="" formVersion="" objectID="" ...>
<data/>
<linked-resources>
<notes/>
<tags/>
<attachments />
<linked-resources/>
<submission-item/>
<submission-batch/>
```
Why the `server-meta` -> `linked-resources` change ? It made more sense to name the node `linked-resources` since it predominantly includes resources linked to the submission rather than metadata for the submission.
Closes #2107
> Add metadata fields present in the JSON response to the XML response

- onadata/libs/utils/logger_tools.py
> Add enketo encryption namespaces

- onadata/libs/tests/utils/test_analytics.py
- onadata/libs/utils/analytics.py
Removes user email information from the user metric data pushed to google analytics via segment.
Updated tests
Closes onaio/zebra#6412
> Withdraw user email from user activity metric data

- onadata/apps/api/viewsets/data_viewset.py
- onadata/libs/tests/utils/test_export_tools.py
- Ensure exports are generated when a submission is deleted
- Added test
N/A
Closes #2130
> Ensure exports are generated on submission delete

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Ensure sort filter is applied for paginated responses from the data endpoint.
Closes #2108
> Ensure Pagination and sorting are implemented on the data endpoint

- docker/onadata-uwsgi/Dockerfile
- Ensure the `libpcre3` packages required to enable uWSGIs  [internal routing](https://uwsgi-docs.readthedocs.io/en/latest/InternalRouting.html) are present
- Run the docker image
N/A
~- [ ] Included tests~
~- [ ] Updated documentation~
> Ensure internal routing is supported on the onadata-uwsgi docker image

- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/api/viewsets/briefcase_viewset.py
- Add a trigger that can be used to disable the removal of the namespace
- Remove namespace attribute from returned XML if present
- Added tests
The  submission XML given to briefcase will now no longer include a namespace; Briefcase adds a namespace when pulling submissions from the server.
Closes #1790
Closes #1763
> Remove namespace attribute from returned XML if present

- onadata/apps/api/viewsets/connect_viewset.py
> Ensure that user_profile is serialized before caching

- onadata/apps/api/tests/viewsets/test_merged_xform_viewset.py
- onadata/apps/api/tests/viewsets/test_metadata_viewset.py
- onadata/apps/api/viewsets/metadata_viewset.py
- onadata/apps/logger/models/xform.py
- onadata/apps/main/models/meta_data.py
- Clean out Merged Datasets upon xform deletion.
- Clean out Form Media Files upon form deletion.
- Add documentation on clean up of filtered datasets
Closes #1029
> Delete xform linked resources upon xform deletion

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/parsed_instance_tools.py
- Test ability to query data whose submission review status is `NULL`
- Submission review status `PENDING` can be thought of in 2 ways:
- Status `3` - For instances when the user had already provided a status, i.e approved/rejected and would like to return submission review status to pending.
- Status `NULL` - By default, if no review has been provided for the submission.
Closes #2112
> Query data endpoint by submission review. Filter `NULL` review status

- onadata/apps/api/viewsets/briefcase_viewset.py
- Utilize XForm `num_of_submissions` instead of trying to count all the instances when `numEntries` is not specified
- Count `instances` using `len()` instead of `count()` to avoid an additional Database query & preload the `instances` before the render
- Only retrieve the `pk` & `uuid` columns from the database instead of all the instance table columns; The briefcase viewset does not utilize any of the other columns
- N/A
Improved performance on the briefcase viewset. Performance gain
- Decreased no. of queries for requests with numEntries query param:
- Decreased no. of queries for requests with the numEntries query param:
_Tests were done on a form with 4601 submissions_
Closes #
> Query optimization for the Briefcase viewset

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/apps/api/viewsets/charts_viewset.py
test on charts by grouping multiple fields.
test on charts with content-type as application/JSON
update the format to JSON in the even content type has been provided
tested locally and used the unit test
N/A
- [ x] Included tests 
Closes #
#2089
> Fix charts groupby multiple fields and check content type 

- onadata/apps/api/tests/viewsets/test_stats_viewset.py
- onadata/libs/data/query.py
Queries for a form collaborators with a lot of submissions  are taking  like 8 mins. We can improve this if we can fetch the data from the user model. 
Testing this and the result are as below
```
Querying using the json field took 528732.595 ms 
Querying with left join took 10016.579 ms
```
Tests added and tested on
Closes #2163
> Use auth user model for _submitted_by field

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/apps/api/viewsets/charts_viewset.py
- Default the response format on the charts endpoint to `JSON` if not format is passed
The charts endpoint will always return a JSON response if the `format` query param is empty
Related to #2151 
_Main reason for the update is because the browser would still return a `Not supported` error with the changes introduced in #2151; Which wasn't the ideal scenario for an API.... If the format is not specified we should always default to JSON IMO_
> Default response format to JSON

- CHANGES.rst
- onadata/__init__.py
- Ignore form permissions when an Export is from a public form. PR #2164 [@DavisRayM]
- Fix charts group by multiple fields and check content type. PR #2151 [@LeonRomo]
- Fix CSV import overwrite which only updated the soft-deleted submissions. PR #2166 [@denniswambua]
- Use auth user model for _submitted_by field stats query. PR #2167 [@denniswambua]
- Bump ona-oidc version to `86d8cd`. PR #2169 [@DavisRayM]
- Default response format to JSON for the Charts endpoint. PR #2170 [@DavisRayM]
- XForm permissions will be ignored for exports made for public XForms
- CSV Import `override` functionality will now always re-create an Instance; It will not take into account the previously imported `UUID`
- The chart endpoint will default to a JSON response if the requested format is not supported
> Tag release v2.5.12

- onadata/libs/tests/utils/test_csv_import.py
- onadata/libs/utils/csv_import.py
Add support for handling CSV columns when the field is a group or a repeat. Ensure's the correct validation and field formatting especially for dates is applied to fields in during a CSV import of data.
Added a test.
None
- [ x] Included tests 
Closes #
> Handle columns in groups and repeats in get_columns_by_type()

- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/libs/filters.py
- onadata/libs/permissions.py
- Enforce XForm meta permissions on the attachment viewset
N/A
> Enforce XForm meta permissions on the attachment viewset

- CHANGES.rst
- onadata/__init__.py
- Disable ARM Docker builds. PR #2171
- Bump ona-oidc version. PR #2172, PR #2175
- Handle columns in groups and repeats in get_column_by_type. PR #2131
- Enforce XForm meta permissions on the attachment viewset. PR #2178.
- Use cache to store submission stats. PR #2176
> Bump version to v2.5.13

- onadata/apps/api/management/commands/create_user_profiles.py
- onadata/apps/api/tests/management/commands/test_create_user_profiles.py
- Added management command to add user profiles to user/org accounts with missing profiles. Noticed that this might happen if a user is created on python shell.
- Added tests to ensure a user without a user profile has one assigned to them on running the management command.
- None
Closes #2160
> 2160 fix users without user profiles

- onadata/apps/main/management/commands/send_email_w_attachment.py
- Add command that can send an email with attachment
> Add command that can send an email with an attachment

- CHANGES.rst
- onadata/__init__.py
- Handle uncaught `StopIteration` exception. PR #2192 
- Add a management command that can send out an email with an attachment. PR #2193
- Utilize queryset iterators for permission retrieval. PR #2189
> Bump version to `2.5.15`

- .github/workflows/ci.yml
- onadata/apps/api/tests/fixtures/Transportation Form.xml
- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/main/tests/fixtures/transportation/transportation.xml
- onadata/apps/main/tests/fixtures/transportation/view/downloadSubmission.xml
- onadata/apps/restservice/services/textit.py
- Generate a copy of the JSON `keys` instead of using the original keys within the dict
N/A
Closes #2196
> Avoid `RuntimeError` caused by using keys modified in loop

- docs/charts.rst
- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/apps/api/viewsets/charts_viewset.py
Adds a `refresh` query param that can be used to invalidate the Charts
cache and recalculate the updated cache
Related to: https://github.com/onaio/zebra/issues/6628
> Add `refresh` query param to invalidate charts cache

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Test that the pagination headers returned while querying are accurate
- Count returned queryset if the `query` param is present
N/A
Closes #2203
> Ensure returned pagination headers are correct when querying for specific values

- onadata/libs/utils/export_builder.py
- Fix `str_to_bool` circular import
Closes #
> Fix export builder circular import

- onadata/libs/utils/export_tools.py
- Use the `use_master` context after first failure when trying to retrieve an external export
N/A
N/A
> Handle cases where an export object is not retrievable when creating an external export

- .gitignore
- onadata/libs/authentication.py
- onadata/libs/tests/test_authentication.py
- Update the `get_api_token` function to raise an `AuthenticationFailed` expection instead of a 404
- A 404 status code will no longer be raised if the provided cookie does not point to an existing token object
Closes #2218
> Return an `AuthenticationFailed` exception instead of a 404 when Enketo token is not retrievable

- CHANGES.rst
- onadata/__init__.py
- Install uwsgitop on the docker builds. PR #2216
- Handle cases where an export object is not retrievable when creating an external export. PR #2220
- Bump ona-oidc version to v0.0.10. PR #2221
- Return an AuthenticationFailed exception instead of a 404 when Enketo token is not retrievable. PR #2219
> Tag release `v2.5.20`

- onadata/libs/serializers/metadata_serializer.py
- onadata/libs/tests/serializers/fixtures/sample.geojson
- onadata/libs/tests/serializers/test_metadata_serializer.py
- onadata/settings/common.py
Use [add_mimetypes](https://docs.python.org/3/library/mimetypes.html#mimetypes.add_type) to add `geojson` type
Added a test case
N/A
> Allow geojson file uploads

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/celery.py
- onadata/libs/utils/common_tools.py
- requirements/base.pip
- requirements/dev.pip
- setup.cfg
Switched to using [`sentry-sdk`](https://docs.sentry.io/platforms/python/migration/) instead of  `raven` which is now under maintenance mode.
Closes #2250
> Use sentry-sdk

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/libs/serializers/geojson_serializer.py
- onadata/libs/tests/serializers/test_geojson_serializer.py
- Add geojson [simplestyle-spec](https://github.com/mapbox/simplestyle-spec/tree/master/1.1.0) support
- Optionally add `title` param to geojson properties
- Add `simple_style` query param to enable simplestyle-spec
URL Example: `https://stage-api.ona.io/api/v1/data/205.geojson?geo_field=trap_coordinates&simple_style=true&title=field_1`
Closes #2240
> Add geojson simplestyle-spec support

- .prospector.yaml
- .pylintrc
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/logger/tests/models/test_instance.py
- onadata/apps/main/tests/test_form_api.py
- onadata/apps/viewer/models/parsed_instance.py
- requirements/base.pip
- requirements/dev.pip
- setup.cfg
Using the `json.loads()` to return field values as default type. Django switched from this approach [here](https://github.com/django/django/blob/e96320c91724830034033a9cb8afd9cf8c11e2fd/django/db/backends/postgresql/base.py#L235).
```
GET /api/v1/data/{form pk}.json?fields=["_id", "_xform_id_string"]
[{"_id": 1, "__xform_id_string": "id_string"}, {"_id": 2, "__xform_id_string": "id_string"}, ..]
```
instead of 
```
GET /api/v1/data/{form pk}.json?fields=["_id", "_xform_id_string"]
[{"_id": "1", "__xform_id_string": "\"id_string\""}, {"_id": "2", "__xform_id_string": "\"id_string\""}, ..]
```
Closes #2254
> Fix data type of filtered /data JSON response

- onadata/apps/main/tests/test_process.py
- onadata/apps/viewer/models/data_dictionary.py
- Upadate to use file object intsead of absolute file path when loading excel workbook
- The following exception is being thrown when uploading a form with external choices
```
File "/srv/onadata/./onadata/apps/viewer/models/data_dictionary.py", line 246, in set_object_permissions
f = sheet_to_csv(instance.xls, "external_choices")
File "/srv/onadata/./onadata/apps/viewer/models/data_dictionary.py", line 76, in sheet_to_csv
workbook = openpyxl.load_workbook(xls_content.path)
File "/usr/local/lib/python3.9/dist-packages/django/db/models/fields/files.py", line 59, in path
return self.storage.path(self.name)
File "/usr/local/lib/python3.9/dist-packages/django/core/files/storage.py", line 128, in path
raise NotImplementedError("This …
```
> Use xlsx file object instead of absolute path

- docker/onadata-uwsgi/Dockerfile
> Add netcat to allow liveness/readiness probes that make use of open port checks.

- onadata/apps/logger/management/commands/generate_platform_stats.py
- Add `include_extra` flag; When the optional argument is present the generated statistics will include Organization and User Info.
Closes #
> Update `generate_platform_stats` management command

- .flake8
- onadata/libs/utils/image_tools.py
- Ensure S3 Client is configured when generating pre-signed URL
- Sets the default signature version for presigned URLs to `s3v4`
Closes #
> Ensure S3 Client is properly configured when generating a presigned URL

- .github/workflows/ci.yml
- onadata/libs/utils/csv_builder.py
Handles the case of a repeat construct in the data but the form
has no repeat construct defined using begin repeat, for example
when you have a hidden value that has a repeat_count set within
a group.
- imported the client data and attempted to do CSV exports; export was successful.
Closes https://github.com/onaio/onadata/issues/2217
> [csv_builder] handle data only repeat structure

- onadata/libs/serializers/share_project_serializer.py
- onadata/libs/tests/serializers/test_share_project_serializer.py
- Remove username max_length constraint in ShareProjectSerializer
Closes #2308
> Remove username `max_length` constraint in ShareProjectSerializer

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/permissions/test_permissions.py
- onadata/apps/main/urls.py
- onadata/libs/serializers/data_serializer.py
- onadata/libs/tests/serializers/test_data_serializer.py
- Reorder ODK submission endpoints
-  Update submission permissions
- ODK submissions are working
part of https://github.com/onaio/zebra/issues/6353
> Order submission urls correctly

- docs/forms.rst
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- Enable pagination when listing forms
- Tests
> Add pagination to forms endpoint

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/libs/serializers/organization_member_serializer.py
- Set organization role to org members and ensure that the org project is shared with the members team in an organization
- Added test to ensure that xform and project permissions are correctly applied to org members
- None
Closes #2322
> Fix org members permissions

- .github/workflows/ci.yml
- .github/workflows/docker-image-build.yml
- .github/workflows/ecr-image-build.yml
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_media_viewset.py
- onadata/libs/tests/utils/test_image_tools.py
- Stop usage of deprecated `set-output` command. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Split CI workflow into separate jobs:
Static Analysis -> Unit Tests
&
Trivy security checks
N/A
> Update Github Action workflows

- .github/workflows/ci.yml
- docker/onadata-uwsgi/Dockerfile
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/logger/tests/test_briefcase_client.py
- onadata/apps/main/tests/test_process.py
- onadata/libs/utils/image_tools.py
- requirements/azure.in
- requirements/azure.pip
- requirements/base.pip
- requirements/dev.pip
- requirements/s3.in
- requirements/s3.pip
- requirements/ses.in
- requirements/ses.pip
- setup.cfg
- Update Django, JWCrypto & OAuthLib requirements
- Update `generate_media_download_url` function to fit into the test categories when s3 dependency is not installed
- Update flaky tests
- Isolate media directory for tests that might delete/modify resources of another test.
- Run test synchronously when another test modifies it's requirements in the same test case i.e deleting a form e.t.c
> Update dependencies and `generate_media_download_url` function

- onadata/libs/tests/utils/test_api_export_tools.py
- onadata/libs/utils/api_export_tools.py
- Delete invalid google OAuth credential and ask users to re-create them
- Added a test case
- N/A
> Ask users to provide a new google oauth credential if current one is invalid

- onadata/libs/models/share_project.py
- onadata/libs/tests/utils/test_project_utils.py
- onadata/libs/utils/project_utils.py
> Propagate project permissions to all KPI Assets

- onadata/apps/api/tools.py
- onadata/apps/main/models/user_profile.py
- onadata/libs/permissions.py
- onadata/libs/serializers/organization_member_serializer.py
- onadata/libs/serializers/organization_serializer.py
- onadata/libs/serializers/project_serializer.py
- onadata/libs/serializers/xform_serializer.py
- onadata/libs/tests/test_permissions.py
- Ensure user profiles are created before building user permissions object
- Tests
- N/A
Closes #2343
> Ensure user profiles exist when building user permissions dict

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/apps/api/tests/viewsets/test_legacy_exports.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/dataview_viewset.py
- onadata/apps/main/tests/test_form_errors.py
- onadata/apps/main/tests/test_form_exports.py
- onadata/apps/main/tests/test_process.py
- onadata/apps/main/urls.py
- onadata/apps/viewer/models/export.py
- onadata/apps/viewer/tasks.py
- onadata/apps/viewer/templates/map_embed.html
- onadata/apps/viewer/tests/test_export_list.py
- onadata/apps/viewer/tests/test_exports.py
- onadata/apps/viewer/tests/test_tasks.py
- onadata/apps/viewer/views.py
- onadata/libs/templates/topbar.html
- onadata/libs/tests/utils/test_export_builder.py
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/api_export_tools.py
- onadata/libs/utils/export_builder.py
- onadata/libs/utils/export_tools.py
- Ensure excel exports are in `xlsx` format instead of `xls`
- Tests
- All excel exports will be in the `xlsx` format
Closes #
> Ensure excel exports are in xlsx format

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/apps/api/tests/viewsets/test_merged_xform_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/api/viewsets/dataview_viewset.py
- onadata/apps/api/viewsets/merged_xform_viewset.py
- Add `GeoJsonRenderer` and a way to return data as geoJSON for:
- `MergedXFormViewset`
- `DataViewViewset`
- Added test cases
Closes https://github.com/onaio/onadata/issues/2359
> Render filtered datasets and merged datasets as geojson

- onadata/libs/authentication.py
- Ensure that the `user` row is selected alongside the token
Closes #2361
> Ensure that the `user` row is selected alongside the `Token`

- .github/workflows/ci.yml
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/export_tools.py
- Filter out deleted submissions when linking a dataset as GeoJSON
- Tests
- The exported GeoJSON will only have active submissions
Closes #
> Filter out deleted submissions from linked geojson

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/apps/api/viewsets/dataview_viewset.py
- Fix choice labels bug on filtered dataset xlsx and CSV exports
- Tests
Closes #
> Fix choice labels bug on filtered dataset exports

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/libs/filters.py
- [Prefix keys in filtered dataset kwargs with 'instance__'](https://github.com/onaio/onadata/pull/2380/commits/18b95bc49ebed1e2e359d8197f10a627b75b5524)
- This will allow filtering attachments using the filtered dataset query
Closes https://github.com/onaio/onadata/issues/2379
> Prefix keys in filtered dataset kwargs with 'instance__'

- .github/workflows/ci.yml
- onadata/apps/api/tests/viewsets/test_metadata_viewset.py
- onadata/libs/serializers/metadata_serializer.py
- onadata/libs/utils/image_tools.py
Adds azure token to metadata media file urls to allow downloading of media files
Added test to confirm if the token is included on the url
partof https://github.com/onaio/zebra/issues/7403
> Add azure token to media files urls

- onadata/apps/viewer/parsed_instance_tools.py
- onadata/apps/viewer/tests/test_parsed_instance.py
Fixes vulnerability reported [here](https://github.com/onaio/onadata/security/code-scanning/757)
Closes #
> Pass user-provided values as parameters

- onadata/apps/api/tests/viewsets/test_export_viewset.py
- onadata/libs/filters.py
- onadata/libs/renderers/renderers.py
- Allow authenticated users to download public form exports
- Fixes `AssertionError: renderer returned unicode, and did not specify a charset value` for .zip, .savzip and .csvzip exports
- Added tests
Part of  https://github.com/onaio/zebra/issues/7439
> Allow authenticated users to download public form exports

- .gitignore
pyenv-virtualenv uses the file **.python-version** to automatically activate the local environment for the project.
> ignore .python-version

- onadata/apps/restservice/signals.py
- onadata/libs/utils/logger_tools.py
the bug was raised by Celery and succeeded the bug `ParsedInstance DoesNotExist`. The ParsedInstance was being read immediately after being created which means it was not guranteed to be available in the replica. The fix applied is to read the created ParsedInstance from the master database
Closes #2282
> fix bug NoneType object has no attribute push

- onadata/libs/serializers/user_profile_serializer.py
- onadata/libs/tests/serializers/test_user_profile_serializer.py
- Display error message when users register using numeric usernames
- Tests
- No user will be allowed to register to the platform with numeric usernames
Closes #2406
> Prevent numeric usernames on user creation

- .github/workflows/docker-image-build.yml
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/tests/test_briefcase_client.py
- onadata/apps/main/tests/fixtures/hxl_test/hxl_example_2.xml
- test(xform): drop support for python2
- test(briefcase): split briefcase client tests into separate test cases
N/A
Less flaky tests
> Isolate flaky test cases

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/libs/serializers/organization_member_serializer.py
- test: ensure that the default team role is assigned to new members
- style: add missing ','
- refactor: grant members of an organization the default team permissions
- refactor: allow empty `role` value to be passed to function
- test(org projects): ensure user isn't granted permissions on projects with no default role
This affects how permissions are assigned to managers and regular members of an organization.
- Managers will be granted the `members` team default role on all the organizations project whenever they join an organization; This is a change from how previously managers would be granted the manager role on all the organization projects
- Managers will be granted the `manager` role for all projects they created; This happens when they join an organization as a manager too.
- …
> Assign default team project role to users

- .github/workflows/ecr-image-build.yml
- CHANGES.rst
- docker/onadata-uwsgi/Dockerfile.ubuntu
- onadata/__init__.py
- setup.cfg
- Bump version to v3.9.0
* ignore .python-version by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2402
* Update `savreaderwriter` version by @DavisRayM in https://github.com/onaio/onadata/pull/2399
* Switch to an Alpine based release image by @DavisRayM in https://github.com/onaio/onadata/pull/2389
* Bump action versions by @DavisRayM in https://github.com/onaio/onadata/pull/2410
* Isolate flaky test cases by @DavisRayM in https://github.com/onaio/onadata/pull/2404
* Add azure token to media files urls by @ciremusyoka in https://github.com/onaio/onadata/pull/2388
* Handle scenario where an inactive user is part of an Organization by @DavisRayM in https://github.com/onaio/onadata/pull/2374
* Allow authenticated users to download public form exports by @ciremusyoka in …
> Tag release v3.9.0

- onadata/apps/restservice/services/generic_json.py
- Handle unhandled connection error while sending webhooks
- Add configurable timeout for Generic JSON REST Services
N/A
Closes #2418
> Add configurable timeouts for webhook requests

- onadata/apps/main/urls.py
- onadata/libs/tests/utils/test_analytics.py
- onadata/libs/utils/analytics.py
- onadata/settings/common.py
- Add postman to list of user agents in the analytics module
- Fix `UnboundLocalError` exception thrown for uninitialized `event_source` var
Closes #2424 and #2427
> Fix unbound local error exception

- onadata/apps/api/tests/viewsets/test_tableau_viewset.py
- onadata/apps/api/viewsets/v2/tableau_viewset.py
- onadata/settings/github_actions_test.py
Fix the peculiar intermittent bug where after applying pagination on the `GET api/v2/open-data/<uuid>/data` endpoint, the server timeouts if the number of submissions is one but seems to have no problem if the number of submissions is more than 1
The fix involves ordering the results only when the queryset returns more than 1 result and only calling the pagination class if the result is more than 1
At the moment, it is not known how applying ordering on the queryset causes the execution to get stuck when getting the first item and not the rest of the items
Other enhancements to optimize the queryset was to make use of [only()](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#django.db.models.query.QuerySet.only) to ensure we only get the field(s) we are accessing and the use …
> fix open-data endpoint timeout bug

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- Add functionality to permanently delete submissions from db
- Added feature flag `ENABLE_SUBMISSION_PERMANENT_DELETE` to optionally enable/disable the functionality
- Tests
Closes #2431
> Add ability to permanently delete submissions

- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/logger/templates/downloadSubmission.xml
- onadata/apps/logger/tests/test_briefcase_api.py
- onadata/apps/main/tests/fixtures/transportation/view/downloadSubmission.xml
- onadata/apps/viewer/tests/test_attachment_url.py
- onadata/apps/viewer/views.py
Optimize attachment endpoint performance by querying attachments using `pk` instead of `media_file` field when using ODK briefcase
Tests
Closes #
> Optimize attachments endpoint

- onadata/apps/api/tests/viewsets/test_tableau_viewset.py
- onadata/apps/api/viewsets/v2/tableau_viewset.py
- onadata/libs/pagination.py
An improvement to the enhancements implemented [here](https://github.com/onaio/onadata/pull/2435)
- Use raw SQL queries to improve the performance of endpoint `GET api/v2/open-data/<uuid>/data`
- Remove ordering of the results by `id` in ascending order since when the number of submissions is large the query is extremely slow. There is also no reason to order the results by default. The consumers of the endpoint can carry out that functionality by themselves
Faster response times for endpoint `GET api/v2/open-data/<uuid>/data`
Closes #
> Enhance performance of open-data endpoint `api/v2/open-data/<uuid>/data`

- .flake8
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/api/viewsets/xform_viewset.py
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/api_export_tools.py
- Fix **AttributeError: 'ExportBuilder' object has no attribute 'to_google_sheets'** raised when google export is not enabled by performing validation during data export. Raise `403` HTTP status if validation fails
- Ignore Flake 8 rule [Line break occurred before a binary operator](https://www.flake8rules.com/rules/W503.html)
Closes #
> Fix AttributeError: 'ExportBuilder' object has no attribute 'to_google_sheets'

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
- Bump version to v3.11.0
- Ensure onadata can work in a multi-domain setup
`PR #2450 <https://github.com/onaio/onadata/pull/2450>`
[@FrankApiyo]
- Add ability to create, update project invitations
`PR #2430 <https://github.com/onaio/onadata/pull/2430>`
- Fix AttributeError: 'ExportBuilder' object has no attribute 'to_google_sheets'
`PR #2458 <https://github.com/onaio/onadata/pull/2458>`
- Fix AttributeError: 'NoneType' object has no attribute 'strip' when exporting form data
`PR #2453 <https://github.com/onaio/onadata/pull/2453>`
- Enhance performance of open-data endpoint api/v2/open-data/<uuid>/data
`PR #2456 <https://github.com/onaio/onadata/pull/2456>`
> Tag release v3.11.0

- .gitignore
- onadata/apps/api/tests/viewsets/test_tableau_viewset.py
- onadata/apps/api/viewsets/v2/tableau_viewset.py
- onadata/libs/pagination.py
- onadata/libs/tests/test_pagination.py
- Fix bug on endpoint  `/api/v2/open-data/<id>/data` where records returned in previous pages appear in future pages
- Fix bug where with each increase in page number, the number of results returned increased by a 100
Closes #
> Fix pagination on endpoint `/api/v2/open-data/<id>/data` returning duplicates

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/viewer/models/data_dictionary.py
Django [`post_save` signal is run at the end of of the Model.save() method](https://docs.djangoproject.com/en/4.2/ref/signals/#post-save). It is not guaranteed that the transaction will have commited at this time. This leads to situation where `XForm.DoesNotExist` exception is at times raised when a new form is created which results in users not having the correct permissions for some forms despite having the appropriate roles
[Use transaction.on_commit](https://docs.djangoproject.com/en/3.2/topics/db/transactions/#performing-actions-after-commit) to ensure `set_project_perms_to_xform_async.delay` in the `post_save` signal is only called after the transaction is successful
[Adjust failing tests to accommodate the new change](https://docs.djangoproject.com/en/3.2/topics/db/transactions/#use …
> Solve intermittent bug where form permissions are not applied for new forms

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.12.2
- Solve intermittent bug where form permissions are not applied for new forms
[PR #2470](https://github.com/onaio/onadata/pull/2470>)
- Enhance performance when exporting data on endpoint `api/v1/data/<form_id>.<format>`
[PR #2460 ](https://github.com/onaio/onadata/pull/2460)
> Tag release v3.12.2

- onadata/apps/logger/models/instance.py
- onadata/apps/logger/tests/test_form_submission.py
Use transaction.on_commit() to ensure the post_save signal that updates submission count is executed only when a transaction is completed. More info on this change can be found [here](https://ken-dev.info/django-tricks/2019/10/04/django-signals-in-transaction.html)
Closes #
> Fix async submission count discrepancy

- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/api/viewsets/briefcase_viewset.py
- onadata/apps/main/urls.py
Add project and form level odk submission list and download list filtering
Allows form and project level granularity of odk submission list and download list
Closes #
> Add project and form level odk submission-list and download endpoints

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.13.0
- Fix async submission count discrepancy
[PR #2469](https://github.com/onaio/onadata/pull/2469>)
[@KipSigei ]
- Add project and form level odk submission-list and download endpoints
[PR #2451](https://github.com/onaio/onadata/pull/2451)
[@KipSigei ]
> Tag release v3.13.0

- onadata/apps/viewer/tests/test_attachment_url.py
- onadata/apps/viewer/views.py
- Ensure sas token is appended to azure blob attachment url
- Test case to ensure token is included on the url
Closes #
> Ensure sas token is appended to azure blob attachment url

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.14.0
- Ensure sas token is appended to azure blob attachment url
[PR #2482](https://github.com/onaio/onadata/pull/2482)
[@KipSigei]
- Data endpoint enhancements
[PR #2477](https://github.com/onaio/onadata/pull/2477)
- Ensure geotrace and geoshape in repeats is included in GeoJSON data endpoint
[PR #2478](https://github.com/onaio/onadata/pull/2478)
[@KipSigei]
> Tag release v3.14.0

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to 3.14.1
- Rebuilding to pick the latest google export changes.
> tag release v3.14.1

- onadata/apps/logger/models/instance.py
When asynchronous processing of submissions is enabled, submissions whose json is not yet processed have an empty json on endpoint /api/v1/data/<form_id>. To prevent this from happening, we save the XML to json data during pre-save. The json will later be updated to include the metadata in the post_save signal
Get rid of records with empty json on endpoint `/api/v1/data/<form_id> when processing submissions asynchronously
Closes #
> Save xml to json data in pre-save

- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/api/viewsets/xform_list_viewset.py
- onadata/libs/renderers/renderers.py
Stream response on endpoint `/<username>/xformsManifest/<form_id>` to avoid the requesting from timing out when the number of records is large 
No side-effects
Closes #
> Stream response on endpoint `/<username>/xformsManifest/<form_id>`

- onadata/apps/logger/models/instance.py
- onadata/libs/filters.py
- Update `_xform_filter` to handle attachments
Closes #
> Improve performance for attachments xform meta permissions check 

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to 3.14.4
- Bump oidc version to v1.0.3
PR #2501
- Improve performance for attachments xform meta permissions check
PR #2499
[@KipSigei]
- Create user auth token if doesn't exist upon retrieval
PR #2496
[@ciremusyoka]
> Tag release v3.14.4

- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/views.py
- onadata/libs/utils/logger_tools.py
Don't call `xform.delete()` method which soft deletes
> Soft delete xform from legacy UI

- .github/workflows/ci.yml
- requirements/base.pip
- requirements/dev.pip
- setup.cfg
- Update patch to 3.2.23 which addresses vulnerability [CVE-2023-46695](https://avd.aquasec.com/nvd/cve-2023-46695)
- Upload Trivy results to security tab on pull request 
- Trivy results are uploaded to Github security tab on pull request
Closes #
> Upgrade Django to version 3.2.23

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.15.0
- Upgrade Django to version 3.2.23
https://github.com/onaio/onadata/pull/2507
- Custom project invitation template
https://github.com/onaio/onadata/pull/2506
- Soft delete xform from legacy UI
https://github.com/onaio/onadata/pull/2503
[@FrankApiyo]
> Bump version to v3.15.0

- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/api/viewsets/briefcase_viewset.py
- Add Optimization Fence in Briefcase Viewset to handle `canceling statement due to statement timeout` OperationalError Exception
- Added a try catch block to execute the optimization fence query when OperationalError Exception is thrown
Closes #
> Enhancement: Handle Statement Timeout in Briefcase Viewset

- requirements/azure.in
- requirements/azure.pip
- requirements/s3.in
- requirements/s3.pip
- requirements/ses.in
- requirements/ses.pip
The previous upgrade had only targeted dev.pip and base.pip and omitted the other requirements file
Closes #
> Upgrade Django for omitted requirements files

- onadata/apps/logger/templatetags/customize_template_by_domain.py
- onadata/apps/logger/tests/test_customize_template_by_domain.py
- Allow customizing of django HTML templates: 
- Add custom template tag; `settings_value`
- Added tests
> Add custom template tag: settings_value

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
- Add custom template tag: settings_value
`PR #2510 <https://github.com/onaio/onadata/pull/2510>`
[@FrankApiyo]
- Enhancement: Handle Statement Timeout in Briefcase Viewset 
`PR #2508 <https://github.com/onaio/onadata/pull/2508>`
[@KipSigei]
- Trigger database call to correctly capture OperationalError
`PR #2513 <https://github.com/onaio/onadata/pull/2513>`
[@KipSigei]
- Upgrade Django for omitted requirements files
`PR #2512 <https://github.com/onaio/onadata/pull/2512>`
> Bump version to v3.16.0

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/viewsets/project_viewset.py
- Remove soft-deleted forms from project forms list endpoint
- Tests
- The project forms endpoint will only list active forms
Closes #2511
> Filter out soft-deleted xforms from project forms endpoint

- onadata/apps/api/tests/viewsets/test_briefcase_viewset.py
- onadata/apps/api/viewsets/briefcase_viewset.py
- Enable `TokenAuthentication` on ODK briefcase endpoints
- Added tests
- The ODK Briefcase endpoints will work with both Digest Authentication and Token Authentication
Closes #
> Enable `TokenAuthentication` on briefcase viewset

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/restservice/services/generic_json.py
- onadata/apps/restservice/services/textit.py
Use `Instance.get_full_dict()` to when sending data to RapidPro instead of `Instance.json`. `Instance.json` may not be upto date when asynchronous processing of submissions is enabled by the time the call to RapidPro is made
Closes #2521
> Fix stale data sent to RapidPro when asynchronous processing of submissions is enabled

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.17.1
- Enable TokenAuthentication on briefcase viewset
`PR #2523 <https://github.com/onaio/onadata/pull/2523>`
[@KipSigei]
- Fix stale data sent to RapidPro when asynchronous processing of submissions is enabled
`PR #2522 <https://github.com/onaio/onadata/pull/2522>`
> Tag release v3.17.1

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.17.2
- Security Updates
`PR #2529 <https://github.com/onaio/onadata/pull/2529>`
[@KipSigei]
- Enable Token Authentication on Form List API
`PR #2525 <https://github.com/onaio/onadata/pull/2525>`
[@KipSigei]
- Set AWS credentials when generating pre-signed URLS
`PR #2527 <https://github.com/onaio/onadata/pull/2527>`
[@ukanga]
> Tag release v3.17.2

- onadata/libs/utils/image_tools.py
- Ensure to explicitly set AWS_S3_ENDPOINT_URL  in boto3 config when defined in settings
Closes #
> Explicitly set AWS_S3_ENDPOINT_URL in boto3 configs

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.17.3
- Explicitly set AWS_S3_ENDPOINT_URL in boto3 configs
`PR #2540 <https://github.com/onaio/onadata/pull/2540>`
[@KipSigei]
> Tag release v3.17.3

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/libs/data/query.py
- Fix SQL syntax error when grouping by select one on charts endpoint
- Tests
Closes #2543
> Fix SQL syntax error when grouping by select one

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to 3.18.0
- https://github.com/onaio/onadata/pull/2549
[@KipSigei]
- https://github.com/onaio/onadata/pull/2547
> Tag release v3.18.0

- onadata/libs/utils/image_tools.py
Fix error `Invalid endpoint` when fetching media files by setting boto3 `AWS_S3_ENDPOINT_URL` to default to `None` instead of an empty string. When an empty string is passed as the value, it is considered a valid value by the package's implementation
Closes #
> Fix bug invalid endpoint when fetching media files

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.18.1
**Bug fixes**
- https://github.com/onaio/onadata/pull/2551
> Bump version to v3.18.1

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.18.2
**Perfomance improvement**
- Improve perfomance of /status endpoint and add onadata-version to /status endpoint [2558](https://github.com/onaio/onadata/pull/2558)
> Bump onadata version to v3.18.2

- onadata/apps/api/tests/viewsets/test_charts_viewset.py
- onadata/libs/tests/utils/test_csv_builder.py
- onadata/libs/utils/csv_builder.py
- Fix bug where child questions of grouped sections that are children of repeating sections are not ignored during CSV export therefore appearing as extra column headers
- Fix flaky test `onadata.apps.api.tests.viewsets.test_charts_viewset.TestChartsViewSet.test_charts_group_by_select_one`
Closes #2562
> Ignore child questions of grouped sections within repeating sections during CSV export

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v3.19.0
- Security Remediations
`PR #2569 <https://github.com/onaio/onadata/pull/2569>`
[@KipSigei]
- Add Instance History indexing to checksum & uuid fields
`PR #2564 <https://github.com/onaio/onadata/pull/2564>`
[@KipSigei]
- Add migration to update old enketo urls
`PR #2552 <https://github.com/onaio/onadata/pull/2552>`
[@ciremusyoka]
- Ignore child questions of grouped sections within repeating sections during CSV export
`PR #2559 <https://github.com/onaio/onadata/pull/2559>`
> Tag release v3.19.0

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/test_tasks.py
- onadata/apps/api/tests/test_tools.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/tools.py
- onadata/apps/api/viewsets/project_viewset.py
- onadata/libs/models/share_project.py
- onadata/libs/serializers/organization_member_serializer.py
- onadata/libs/serializers/share_project_serializer.py
- onadata/libs/tests/models/test_share_project.py
[Share a project with user](https://github.com/onaio/onadata/blob/main/docs/projects.rst#share-a-project-with-users) asynchronously
[Add user to an organization](https://github.com/onaio/onadata/blob/main/docs/orgs.rst#add-a-user-to-an-organization) asynchronously
Refactor to remove redundant code
Closes #2505
> Add user to organization asynchronously

- onadata/apps/api/tests/viewsets/test_connect_viewset.py
- onadata/apps/api/viewsets/connect_viewset.py
Fix `NoneType` error
Added a test case
`ODKTokens` with `expires` fields set to `None` will be inactivated
Closes https://github.com/onaio/onadata/issues/2584
> When an odk token expires is None, deactivate and replace

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.0.1
**Bug fixes**
- https://github.com/onaio/onadata/pull/2583
- https://github.com/onaio/onadata/pull/2578
> Bump version to v4.0.1

- onadata/apps/logger/models/merged_xform.py
- onadata/apps/logger/models/tests/test_merged_xform.py
- onadata/libs/tests/utils/test_project_utils.py
- onadata/libs/utils/project_utils.py
Refactor to apply permissions for merged dataset asynchronously
Closes #
> Set permissions for merged dataset asynchronously

- .github/workflows/ecr-image-build.yml
Update Github ECR actions to run trivy scans after the docker tags have been pushed.
Closes #
> Move trivy scan after docker image tags have been set

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/tests/test_briefcase_client.py
- onadata/libs/models/share_project.py
- onadata/libs/tests/models/test_share_project.py
Fix merged dataset permissions not applied when a user is added to a project or added to an organization
None
Closes #2596
> Fix merged dataset permissions not applied on share

- onadata/apps/logger/migrations/0014_populate_attachment_xform.py
Run migration as SQL query to optimize performance when number of records to be updated is huge. The migration SQL is
```
WITH logger_attachment_instance AS (
SELECT 
logger_attachment.id, 
logger_instance.xform_id, 
logger_instance.user_id 
FROM 
logger_attachment 
INNER JOIN logger_instance ON logger_attachment.instance_id = logger_instance.id 
INNER JOIN logger_xform T4 ON logger_instance.xform_id = T4.id 
WHERE 
logger_attachment.xform_id IS NULL 
AND T4.deleted_at IS NULL
) 
UPDATE 
logger_attachment 
SET 
xform_id = logger_attachment_instance.xform_id, 
user_id = logger_attachment_instance.user_id 
FROM 
logger_attachment_instance 
WHERE 
logger_attachment.id = logger_attachment_instance.id;
```
The reverse migration SQL query is
```
WITH logger_attachment_xform AS (
SELECT …
```
> Optimize attachment xform migration

- onadata/libs/tests/utils/test_password_validator.py
- onadata/libs/utils/validators.py
- Fix ValueError exception thrown during password validation which happens when the created user instance hasn't been fully committed to database, closes #2603 
Closes #
> Fix ValueError for User instance primary key in password validation

- .github/workflows/ci.yml
- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_viewset.py
- onadata/apps/logger/tests/test_briefcase_client.py
- onadata/libs/authentication.py
Closes https://github.com/onaio/onadata/issues/2617
> Check attempts is truthy before int comparison

- onadata/apps/logger/migrations/0018_entityhistory_entitylistgroupobjectpermission_and_more.py
- onadata/apps/logger/models/entity.py
- onadata/apps/logger/models/entity_list.py
Tune migration performance by disabling automatic creation of indexes by Django and updating the migration with SQL queries to create the indices concurrently.
Indexes of interest were discovered by running the command `python3.10 manage.py sqlmigrate logger 0018_entityhistory_entitylistgroupobjectpermission_and_more`
Migration runs faster in huge databases without locking transactions when the indexes are being created
> Tune migration performance

- onadata/apps/logger/migrations/0019_alter_project_options_and_more.py
- onadata/libs/utils/project_utils.py
Add migration to run code to add permission `add_project_entitylist` to existing owners and managers of a project
> Add migration to `add_project_entitylist` permission to existing owners and managers

- onadata/apps/api/permissions.py
- onadata/apps/api/viewsets/entity_list_viewset.py
- onadata/libs/utils/user_auth.py
Ignore permissions on API endpoints and avoid manually setting model permissions when a user is created. 
Also avoids having a migration to add the EntityList permissions to existing users so that they can access the API
> Ignore EntityList model permissions on API endpoints

- docs/entities.md
- onadata/apps/api/tests/viewsets/test_entity_list_viewset.py
- onadata/apps/api/viewsets/entity_list_viewset.py
Add search filter support for Entities
> Entities search

- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/apps/logger/models/registration_form.py
- onadata/apps/logger/tests/models/test_registration_form.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/logger_tools.py
Add support for creating Entity properties defined within grouped sections
> Add support for defining Entity properties within grouped sections

- onadata/apps/api/models/organization_profile.py
- onadata/apps/api/tests/viewsets/test_abstract_viewset.py
- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/apps/api/viewsets/organization_profile_viewset.py
- onadata/libs/serializers/organization_serializer.py
Add email to the organization profile model & organization serializer
Updated test cases
Closes https://github.com/onaio/onadata/issues/2652
> Add email field to the organization serializer

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.3.4
* Entities search by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2643
* Optimize updates to project `date_modified` field when submitting data by @KipSigei in https://github.com/onaio/onadata/pull/2642
* Add support for defining Entity properties within grouped sections by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2644
* Remove default ordering on XForm, Attachment model by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2645
* Cache XForm manifest data by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2646
* Exclude deleted Entities from form's manifest data by @kelvin-muchiri in https://github.com/onaio/onadata/pull/2648
* Add email field to the organization serializer by @FrankApiyo in …
> Tag release 4.3.4

- onadata/apps/logger/migrations/0020_rename_logger_inst_deleted_at_da31a3_idx_logger_inst_deleted_da31a3_idx_and_more.py
A [previous change](https://github.com/onaio/onadata/pull/2661) to safe rename indexes did not separate database and state hence Django does not recognize that the schema changes were applied. Running `makemigrations` command creates a new migration since the model state and actual state of the database are out of sync.
> Fix untracked Django's view of migration state

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/test_tasks.py
- onadata/apps/api/viewsets/organization_profile_viewset.py
- onadata/libs/utils/logger_tools.py
- Invalidate cache when organization permissions are updated
- User per-role cache key for the organization_profile_viewset
N/A
Closes https://github.com/onaio/onadata/issues/2672
> User per-role cache key for the organization_profile_viewset

- onadata/apps/restservice/signals.py
- onadata/apps/restservice/tasks.py
- onadata/apps/viewer/signals.py
Wait for transaction to complete before calling webhooks
> Wait for transaction to complete before calling webhooks

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_osm_viewset.py
- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/restservice/services/generic_json.py
- onadata/apps/restservice/services/textit.py
- onadata/apps/restservice/signals.py
- onadata/apps/restservice/tasks.py
- onadata/apps/restservice/tests/viewsets/test_restservicesviewset.py
- onadata/apps/viewer/signals.py
- onadata/libs/tests/utils/test_export_tools.py
The data sent to rest services can be stale if the instance is not yet saved to the database when a submission is edited.
We wait until until the transaction completes successfully by using `transaction.on_commit`
Closes #2668
> Fix stale data sent to rest services after editing submission

- docs/entities.rst
- onadata/apps/api/tests/viewsets/test_entity_list_viewset.py
- onadata/apps/api/viewsets/entity_list_viewset.py
Add support for downloading EntityList dataset
> Add support for downloading EntityList dataset

- onadata/apps/api/tests/viewsets/test_organization_profile_viewset.py
- onadata/libs/serializers/organization_serializer.py
Remove email from `validated_data` before updating the organization profile
Updated test cases
Closes https://github.com/onaio/onadata/issues/2676
> Fix exception thrown when updating organization profile

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.5.0
**Features**
- https://github.com/onaio/onadata/pull/2678
- https://github.com/onaio/onadata/pull/2666
- https://github.com/onaio/onadata/pull/2680
- https://github.com/onaio/onadata/pull/2673
- https://github.com/onaio/onadata/pull/2670
- https://github.com/onaio/onadata/pull/2665
**Bug fixes**
- https://github.com/onaio/onadata/pull/2682
- https://github.com/onaio/onadata/pull/2677
- https://github.com/onaio/onadata/pull/2667
> Bump version to v4.5.0

- onadata/libs/tests/test_throttle.py
- onadata/libs/throttle.py
This will throttle anonymous enketo users more fairly
Closes #
> Add CustomScopedRateThrolle throttling class

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/viewsets/test_xform_list_viewset.py
- onadata/apps/api/tools.py
- onadata/apps/api/viewsets/organization_profile_viewset.py
- onadata/apps/api/viewsets/xform_list_viewset.py
- onadata/libs/utils/cache_tools.py
- onadata/libs/utils/logger_tools.py
Cache xform list results by users role. 
Move methods to resolve cyclic dependency errors.
**Limitations**
The cache is only invalidated at expiry time. The expiry time is set at 10 minutes. Cache invalidation when a form is deleted/added will be added in future.
> Cache xform list results

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.6.0
- https://github.com/onaio/onadata/pull/2692
> Bump version to v4.6.0

- onadata/apps/logger/models/instance.py
The post processing actions are part of the write flow and should be pinned to master database. This helps the replicas be more available to serve clients
> Pin submission post processing actions to master database

- onadata/apps/logger/models/project.py
- onadata/apps/logger/models/xform.py
Add missing model index changes. 
Running `makemigrations` command adds migrations to remove the indexes added in migration `onadata/apps/logger/migrations/0024_project_idx_logger_project_deleted_at_and_more.py` because the corresponding changes are missing in the models.
> Add missing model index changes

- onadata/apps/api/tools.py
- onadata/libs/models/share_project.py
Use chunked queryset when iterating queryset
Avoid loading all data into memory
> Use chunked queryset when iterating queryset

- docs/data.rst
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/viewer/parsed_instance_tools.py
- onadata/apps/viewer/tests/test_parsed_instance.py
- onadata/libs/exceptions.py
- onadata/libs/utils/common_tags.py
- requirements/base.in
- requirements/base.pip
- requirements/dev.pip
Add support for OR operation with date fields when filter on endpoint `/api/v1/data`
Closes #2698
>  Add support for `OR` operation data filter for date fields

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.8.0
- https://github.com/onaio/onadata/pull/2708
- https://github.com/onaio/onadata/pull/2704
> Bump version to v4.8.0

- onadata/apps/api/tools.py
Disable sending of activation email when creating organization
No activation email will be sent when creating an organization.
Closes #2669
> Disable sending of activation email when creating organization

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/apps/api/viewsets/dataview_viewset.py
- onadata/libs/serializers/dataview_serializer.py
- onadata/libs/tests/serializers/test_dataview_serializer.py
- Exclude `deleted_by` serializer field
- Filter out dataview that have already been deleted from the dataviews endpoint
Ran locally
N/A
Closes https://github.com/onaio/onadata/issues/2720
> Customized deleted_by serializer field for Dataviews

- onadata/apps/api/tests/viewsets/test_dataview_viewset.py
- onadata/libs/tests/utils/test_csv_builder.py
- onadata/libs/tests/utils/test_export_builder.py
- onadata/libs/utils/csv_builder.py
- onadata/libs/utils/export_builder.py
Fix extra columns e.g `_id` excluded in DataView CSV export
Fix extra columns not included in DataView columns present in other export formats
Fix `openpyxl` deprecated syntax
Extra columns in DataView will be included DataView CSV exports
Only extra columns in Data View will be included on other export formats
Closes #
> Fix extra columns excluded in DataView CSV export

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to v4.9.2
- Security updates
`PR #2729 <https://github.com/onaio/onadata/pull/2729>`
- Invalidate XForm list cache when form is published/replaced
`PR #2730 <https://github.com/onaio/onadata/pull/2730>`
- Update pre commit install instructions
`PR #2723 <https://github.com/onaio/onadata/pull/2723>`
- Update to oidc v1.1.2
`PR #2736 <https://github.com/onaio/onadata/pull/2736>`
[@ukanga]
- Security updates
`PR #2737 <https://github.com/onaio/onadata/pull/2737>`
- Ensure geojson exports creation process is idempotent
`PR #2734 <https://github.com/onaio/onadata/pull/2734>`
[@FrankApiyo]
- [fix] Lookup only models where the parent is h:head
`PR #2733 <https://github.com/onaio/onadata/pull/2733>`
[@ukanga]
> Bump version to v4.9.2 & update changelog

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/test_tasks.py
- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/viewsets/data_viewset.py
- onadata/apps/viewer/models/parsed_instance.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/cache_tools.py
- onadata/libs/utils/logger_tools.py
Delete submissions asynchronously
Track submissions being deleted in cache and exclude them when returning data
Eliminate timeouts when deleting many submissions
Closes #2462
> Delete bulk submissions asynchronously

- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/apps/main/urls.py
- onadata/libs/serializers/data_serializer.py
Validates project ID and form ID are numeric when handling submissions.
Try post a submission to <API URL>/projects/not_numeric/submission.
N/A
Closes https://github.com/onaio/onadata/issues/2719
> fix: value error exception for non numeric project id

- onadata/apps/api/tests/viewsets/test_attachment_viewset.py
- onadata/apps/api/viewsets/attachment_viewset.py
Ensure `xform` GET query parameter is numeric before running DB query to get a record.
Updated test.
N/A
Closes https://github.com/onaio/onadata/issues/2641
> fix: ensure xform GET query parameter  is numeric

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
Bump version to 4.10.0
**Bug fixes**
- https://github.com/onaio/onadata/pull/2743
- https://github.com/onaio/onadata/pull/2742
- https://github.com/onaio/onadata/pull/2741
- https://github.com/onaio/onadata/pull/2744
- https://github.com/onaio/onadata/pull/2738
> Bump version to 4.10.0

- onadata/apps/logger/tests/models/test_instance.py
- onadata/libs/utils/logger_tools.py
fix 'NoneType' object has no attribute 'getAttribute' thrown when import CSV for a form that defines Entities
Resolve CSV import failure for a form that defines Entities
Closes #2753
> Fix CSV import error for a form that defines Entities

- .github/workflows/ecr-image-build-w-arm-runner.yml
- onadata/apps/viewer/models/export.py
- onadata/libs/tests/utils/test_export_tools.py
- onadata/libs/utils/api_export_tools.py
- onadata/libs/utils/export_tools.py
- Add new `EXPORT_OPTIONS` for GeoJSON exports
- Tested locally
- Updated test cases
N/A
Closes #2752
> Add GeoJSON attachment params to EXPORT_OPTIONS

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/api/viewsets/project_viewset.py
- onadata/libs/serializers/project_serializer.py
Add encrypted key to form metadata in ProjectViewSet list
No side effect
Closes #2751
> Add encrypted key to form metadata in ProjectViewSet list

- onadata/apps/api/tests/viewsets/test_abstract_viewset.py
- onadata/apps/logger/tests/models/test_instance.py
- onadata/apps/main/tests/test_csv_export.py
- onadata/apps/viewer/models/data_dictionary.py
- onadata/apps/viewer/models/tests/test_data_dictionary.py
- onadata/libs/tests/utils/test_csv_builder.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/logger_tools.py
Creating a register if it does not exist when an Instance is saved resulted in a bloated queue and load on the database from traversing all submissions for a XForm.
Instances under which we should create the register:
1. When a new form is published
2. When a CSV export is triggered and the register does not exist.
Prevents the queue and database from becoming bloated with requests to traverse all submissions for a form to build the export register when a Instance is saved.
Closes #
> Do not create export register when Instance is saved

- onadata/apps/logger/models/instance.py
- onadata/libs/tests/utils/test_csv_builder.py
Fix exception Instance.DoesNotExist intermittently raised when registering Instance repeats. The exception is raised by Celery task because the Instance has not yet been committed to the database.
Closes #
> Fix exception Instance.DoesNotExist when registering Instance repeats

- onadata/apps/logger/models/instance.py
- onadata/libs/tests/utils/test_logger_tools.py
- onadata/libs/utils/logger_tools.py
This changes allows repeats even from unapproved submissions to be registered as unapproved submissions are usually allowed in exports
Repeats from unapproved submissions are considered during CSV export
Closes #
> Allow unapproved submissions when registering export repeats

- onadata/apps/logger/management/commands/transferproject.py
Fix XForm permissions not applied after transferring project via management command. Assignment of the XForm permissions relies on assignment of Project permissions first
> Fix XForm permissions not applied after transferring project via management command

- docker/onadata-uwsgi/Dockerfile.ubuntu
Fix Package 'openjdk-11-jre-headless' has no installation candidate when building Docker image
The issue is that openjdk-11-jre-headless is no longer available in Debian Bookworm's main repositories. This change uses openjdk-17-jre-headless
> Fix  Package 'openjdk-11-jre-headless' has no installation candidate

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_user_viewset.py
Ensure anonymous users can not list onadata users
- Tested locally with `curl`
- Added unit tests
- Users who are not authenticated will no longer be able to list users using the `/api/v1/users` endpoint
> Ensure only authenticated users can list users

- onadata/apps/api/tests/viewsets/test_project_viewset.py
- onadata/apps/logger/management/commands/transferproject.py
- onadata/apps/logger/tests/test_transfer_project_command.py
- onadata/apps/main/tests/test_base.py
- onadata/libs/serializers/project_serializer.py
Fix forms permissions not updated when project is transferred. Collaborators who are not part of the recipient organization can still access the project and form.
Closes #
> Fix form permissions not updated when project is transferred

- CHANGES.rst
Bump version to v4.13.0
- https://github.com/onaio/onadata/pull/2773
- https://github.com/onaio/onadata/pull/2776
- https://github.com/onaio/onadata/pull/2778
- https://github.com/onaio/onadata/pull/2775
> Bump version to v4.13.0

- onadata/libs/tests/utils/test_export_builder.py
- onadata/libs/utils/export_builder.py
Ensure choices is not None and has the attribute options.
Publish a form with a select_multiple_from_file question on onadata versions 5.0.0 - 5.0.3. Export will fail with an AttributeError exception.
None.
Closes https://github.com/onaio/onadata/issues/2797
> fix: PyXForm question may have choices as None

- onadata/apps/viewer/models/data_dictionary.py
- onadata/apps/viewer/tests/test_data_dictionary.py
- onadata/libs/kms/tools.py
- onadata/libs/tests/kms/test_tools.py
Add support for overriding custom encryption when a form is published and encrypt the form using managed keys.
> Add support for overriding custom encryption

- onadata/apps/api/tasks.py
- onadata/apps/api/tests/test_tasks.py
- onadata/apps/logger/models/instance.py
- onadata/apps/logger/tasks.py
- onadata/apps/logger/tests/models/test_instance.py
- onadata/apps/logger/tests/test_tasks.py
Exclude non-database operations within `transaction.atomic`. Avoid rolling back the transaction if cache operations that succeed, database operations fail
Retry asynchronous tasks on `django.db.OperationalError`
Closes #
> Fix inconsistent XForm num_of_submissions

- onadata/apps/api/tests/viewsets/test_user_profile_viewset.py
- onadata/apps/api/viewsets/user_profile_viewset.py
- onadata/libs/utils/cache_tools.py
Addresses security issue where cache keys only used target username, allowing potential cross-user access to cached profile data.
Changes:
- Update cache keys to include requesting user: `user_profile-{username}{requesting_user}`
- Apply fix to update(), retrieve(), and create() methods in UserProfileViewSet
- Add comprehensive tests to verify cache isolation between users
- Ensure users cannot access other users' cached profile data
This prevents cache poisoning attacks where malicious users could potentially access cached profile information of other users.
Closes #
> Fix cache poisoning vulnerability in UserProfileViewSet

- onadata/apps/api/tests/viewsets/test_data_viewset.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
- onadata/libs/utils/logger_tools.py
Fix submission marked as duplicate if `django.db.IntegrityError` is thrown when saving the submission. The 
`django.db.IntegrityError` will have a HTTP response code of `500` and not `202`
Closes #
> Fix submission marked as duplicate if IntegrityError is thrown

- onadata/libs/tests/utils/test_export_builder.py
- onadata/libs/utils/export_builder.py
- Add null checks before accessing child.bind.get() to prevent AttributeError
- Fix crash when survey contains metadata fields or notes with None bind
- Add regression tests for various None bind scenarios (metadata fields, notes, groups)
Closes #
> Handle None bind attributes in ExportBuilder survey processing

- onadata/apps/logger/migrations/0028_instance_decryption_status_and_more.py
Create index `logger_inst_decrypt_1b32ab_idx` concurrently, which is great for zero downtime for large databases
> Create index concurrently

- onadata/apps/logger/models/xform.py
- onadata/apps/main/tests/test_base.py
- onadata/libs/kms/tools.py
- onadata/libs/tests/kms/test_tools.py
The bug arises from `SurveyElementBuilder.to_json_dict()`generating an incorrect JSON schema when publishing the XLSForm. A `SurveyElementBuilder` object created from an existing `XForm`'s JSON schema generates invalid XML
Closes #
> Fix bug where encrypted XLSForm with choice filter has invalid XML

- onadata/libs/kms/tools.py
- onadata/libs/tests/kms/test_tools.py
Resolve corrupted submission decryption failure reason and status not saved. `valigetta.decryptor.decrypt_submission` returns a generator. Any exception will be raised when the generator is consumed.
Submissions that fail decryption because of corrupted data will have a `decryption_status` of `failed` and a JSON metadata key `_decryption_error` with a value of `INVALID_SUBMISSION`
Closes #
> Resolve corrupted submission decryption failure reason and status not saved

- onadata/apps/logger/models/xform.py
- onadata/apps/logger/tests/models/test_xform.py
- These changes fix a PyXForm error caused by reading a file whose file pointer is not at the beginning
Added unit tests
N/A
Closes https://github.com/onaio/onadata/issues/2903
> Fix form replacement error

- CHANGES.rst
- onadata/__init__.py
- setup.cfg
chore: bump version to v5.6.0
**Features**
- https://github.com/onaio/onadata/pull/2911
> chore: bump version to v5.6.0

- onadata/libs/serializers/password_reset_serializer.py
- onadata/libs/tests/serializers/test_password_reset_serializer.py
- We will no longer send password reset emails to organizations
- Added test cases
N/A
Closes: https://github.com/onaio/onadata/issues/2915
> Only send password reset emails to non-organizations

- onadata/apps/api/permissions.py
- onadata/apps/api/tests/viewsets/test_xform_submission_viewset.py
The project owner's require auth status should be used and not the project creator's require auth status. This bug affected projects within an organization where the project's creator disabled require auth but the organization required auth was enabled. This resulted in a 403 response instead of a 401 for anonymous users.
ODK Collect users will be prompted to entre their credentials instead of receiving a 403 error if the credentials are stale or missing when sending submissions
Closes #2918
> fix: submission using project pk uses creator's require auth status
